### ISSUE TITLE
please add create sub folder tree 

### ISSUE THREAD

**Issue by zarbinet** [canton7/SyncTrayzor#491] opened 2019-01-04 04:22 UTC
syntrayzor portabel >> please add create sub folder tree

**Comment by canton7** [comment] 2019-01-04 12:18
I have no idea what you're asking for I'm afraid. What's a "create sub folder tree"?

**Comment by zarbinet** [comment] 2019-01-06 21:47
like explorer on windows.

**Comment by canton7** [comment] 2019-01-07 10:18
I still have no idea what you're asking.

Please write enough text for another human to work out what you mean, rather than trying to use the bare minimum number of words. Use pictures if that helps.

**Comment by zarbinet** [comment] 2019-01-07 10:32
![image](https://user-images.githubusercontent.com/46364935/50763322-12261b80-12a2-11e9-8741-f79ecba0f345.png)
 Like this brother...

**Comment by canton7** [comment] 2019-01-07 11:37
Wrong repo, and duplicate of an existing Syncthing issue: https://github.com/syncthing/syncthing/issues/2070

**Closed** 2019-01-07 11:37 UTC
Labels: syncthing

**Comment by zarbinet** [comment] 2019-01-08 06:11
ok thanks.sorry
