### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by dtxl** [canton7/SyncTrayzor#367] opened 2017-05-22 08:45 UTC
I just updated SyncTrayzor and got en error:

Version: 1.1.15.0; Variant: Installed; Arch: X86
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.TimeoutException: The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at SyncTrayzor.Services.Ipc.IpcCommsClient.SendCommand(String command) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Ipc\IpcCommsClient.cs:line 52
   at SyncTrayzor.Services.Ipc.IpcCommsClient.ShowMainWindow() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Ipc\IpcCommsClient.cs:line 35
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 122
   at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 80
   at Stylet.BootstrapperBase.<Setup>b__0(Object o, StartupEventArgs e) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 48
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment] 2017-05-22 08:52
Duplicate of #357. Update to 1.1.16, where it as been fixed.

**Closed by canton7** 2017-05-22 08:52 UTC
