### ISSUE TITLE
Please make the integrated browser support touch screen scrolling

### ISSUE THREAD

**Issue by liyafe1997** [canton7/SyncTrayzor#487] opened 2018-11-29 14:34 UTC
Now it only support use the scroll bar to scroll, not support using finger to swipe the page to scroll in touch screen.

**Comment by canton7** [comment] 2018-11-29 19:05
Duplicate of #293, #286, #241, (and see also #129).

The bottom line is that the embedded browser doesn't support touch scrolling, so there's nothing I can do. Sorry.

**Closed by canton7** 2018-11-29 19:05 UTC
