### ISSUE TITLE
1.1.27 crashes after update

### ISSUE THREAD

**Issue by iRomanyshyn** [canton7/SyncTrayzor#612] opened 2021-01-04 12:50 UTC
Hi! I have SyncTrayzor upgraded today on my PC and now it crashes every time I try to start it. There no crash report window and I don't know where to find the logs.

**Comment by iRomanyshyn** [comment] 2021-01-04 13:03
I fixed it by running syncthing.exe manually then synctrayzor.exe started without a crash.

**Comment by canton7** [comment] 2021-01-04 13:04
Weird. Try opening the Event Viewer -> Windows Logs -> Application Logs, and look for things with a red exclamation mark

If you're running anti-virus, also check its logs.

**Comment by canton7** [comment] 2021-01-04 13:11
The logs are in `C:\Users\<You>\AppData\Roaming\SyncTrayzor\logs`. It would be interesting to see if there's anything there as well, even if you've managed to work around it, in case other people hit whatever this issue was as well.

**Comment by teamster22** [comment] 2021-01-04 16:52
I'm also having this same issue. Updated SyncTrazor, and now it crashes on every launch. Log file attached. 
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/5765821/SyncTrayzor.log)

**Comment by canton7** [comment] 2021-01-04 16:59
@teamster22 You have a different issue: for starters you're running 1.1.26, not 1.1.27. Please upgrade to 1.1.27.

**Comment by teamster22** [comment] 2021-01-04 17:06
> @teamster22 You have a different issue: for starters you're running 1.1.26, not 1.1.27. Please upgrade to 1.1.27.

My mistake. Updated, resolved.

**Comment by sfordinc** [comment] 2021-01-19 14:18
I have similar problem:
Version: 1.1.27.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: CefSettings.BrowserSubprocessPath not found.
Имя файла: 'C:\Program Files\SyncTrayzor\CefSharp.BrowserSubprocess.exe'
   в CefSharp.Cef.Initialize(CefSettingsBase cefSettings, Boolean performDependencyCheck, IApp cefApp)
   в SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   в Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   в Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   в Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   в System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   в Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   в Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   в Stylet.ScreenExtensions.TryActivate(Object screen)
   в Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   в Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   в Stylet.WindowManager.ShowWindow(Object viewModel)
   в Stylet.BootstrapperBase.Start(String[] args)
   в System.Windows.Application.OnStartup(StartupEventArgs e)
   в System.Windows.Application.<.ctor>b__1_0(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment] 2021-01-19 15:50
@sfordinc Check whether it's a duplicate of #618, and open a new issue if not.

**Comment by canton7** [comment] 2021-03-06 11:45
Closing as no response. Please comment if you get the logs and I'll re-open. Thanks!

**Closed by canton7** 2021-03-06 11:45 UTC
