### ISSUE TITLE
Multiple Pop Ups

### ISSUE THREAD

**Issue by eyeson** [canton7/SyncTrayzor#122] opened 2015-07-07 15:39 UTC
As per:

https://forum.syncthing.net/t/synctrazor-balloons-saved-up/5124

Locked my computer and left it for a day (Synctrazor was running)

Came back - Stopped syncthing via synctrazor's tray icon. Pop up after pop up continued to appear.. spent a while pressing the cross gave up and waited for them to finish themselves.

Pops up were xxx connect and xxx disconnected, it was like it had saved them up until my computer was unlocked

**Comment by canton7** [comment] 2015-07-07 15:40
Please include the contents of your log (found at `C:\Users\<You>\AppData\SyncTrayzor\logs\SyncTrayzor.log`).

**Comment by eyeson** [comment] 2015-07-07 15:42
Sorry just seen your comment on the forum... The file is massive... all of it?

**Comment by canton7** [comment] 2015-07-07 15:43
In that case it might make most sense to zip it up and email it to me: my email address is on my GitHub profile page.

**Comment by canton7** [comment] 2015-07-07 15:47
(I'm interested in whether 1) Syncthing reported all of the connectivity events at once, 2) It reported them bit by bit, but SyncTrayzor fetched them all at once, or 3) It reported them bit by bit, SyncTrayzor read them as they were reported, but it queued up displaying them until you logged back in)

**Comment by eyeson** [comment] 2015-07-07 15:48
Sent - It may or my not be as expected as I said to me a lot of it looks benign

**Comment by canton7** [comment] 2015-07-07 16:03
OK, it looks like the events are being read as they occur, which means I'm going to have to do some digging...

**Comment by canton7** [comment] 2015-07-07 16:43
Right, I'm having a bit of trouble replicating this on my machine.

I've put a build together which does two things: 1) it introduces some code which *may* work around the issue (depending on what exactly is causing it), and 2) it introduces a bit more logging which should help narrow down the cause if part 1) doesn't work...

The build will be available here: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.26.107/artifacts in about 20 minutes. I'd be grateful if you could install it, and attempt to reproduce the issue.

Thanks!

**Comment by canton7** [comment] 2015-07-13 15:37
Hi, and feedback on this?

**Comment by kozec** [comment] 2015-07-14 07:49
Hi.

If this is about Windows, balloon popup stacking is OS feature there. AFAIK, if popup is to be dismissed by user, it stands there until end of time and any later popup is scheduled to be displayed after.

_(i posted this on forum and then realized it's week old topic; sorry about that)_

**Comment by canton7** [comment] 2015-07-14 08:03
What version of Windows? On Windows 7, I'm seeing new popups replace older ones.

**Comment by kozec** [comment] 2015-07-14 08:17
W7 as well. Maybe it depends on which API is used. I tested it with python & direct WinAPI calls and my test application had same behavior as @eyeson describes.

http://pastebin.com/St3f3M4R

**Comment by canton7** [comment] 2015-07-14 08:21
Interesting. The docs for NOTIFYICONDATA also say that they should be queued, so I'm not sure why I'm seeing them replace.

Also not sure what the best approach would be in that case... Maybe balloons aren't the best medium here?

**Comment by kozec** [comment] 2015-07-14 08:39
Only idea as I have not mean to test it right now. but wouldn't destroying and re-creating notification icon prevent balloons from queuing?

**Comment by canton7** [comment] 2015-07-14 08:44
If you set `szInfo` to an empty string, that will hide the balloon too, I think. The question is whether showing a balloon for a split-second is necessarily the friendliest way of doing it...

**Comment by canton7** [comment] 2015-07-14 09:01
Hrm, I just tried your python sample, and it goes straight for balloon #4.

**Comment by kozec** [comment] 2015-07-15 08:59
That's weird, it doesn't do that on my machine. Maybe it depends on some OS setting...
Anyway, I'm sorry if I let you in wrong direction.

**Comment by canton7** [comment] 2015-07-15 09:18
No it's been helpful thanks - it's confirmed that there's definitely some machine-specific thing going on, rather than small differences in winapi usage.

**Comment by canton7** [comment] 2015-07-16 09:47
This should be fixed in v1.0.27. Let me know if you still see issues.

**Closed by canton7** 2015-07-16 09:47 UTC

**Comment by eyeson** [comment] 2015-07-16 20:15
Sorry have been away - I will upgrade and report back if I have any more of this issue.

**Comment by canton7** [comment] 2015-07-17 08:22
No worries!
