### ISSUE TITLE
FEATURE REQUEST: To have the possibility of starting syncthing and inotify when windows starts

### ISSUE THREAD

**Issue by okibcn** [canton7/SyncTrayzor#372] opened 2017-06-04 02:11 UTC
The current SyncTrayzor can't configure syncthing to start when windows boots. It actually can only be configured to start on logon. It would be nice to have the syncthing and inotify functionality even when no user is logged in. When a user logs in then the user could run synctrayzor to have control of the service that has been running in background.

I tried to install Syncthing as a service with nssm but SyncTrayzon can't take control of the already opened Syncthing process.

**Comment by canton7** [comment] 2017-06-04 09:01
This is a duplicate of another issue, but I can't find it at the moment...

This is quite a bit more complex than you think, and would require a major rewrite of the application. Think about how to support multiple users in a way which doesn't allow one user to access another user's files, for instance. It also wouldn't work for the portable version.

Unless I get made redundant and have a few weeks' spare time, there's no point even trying to design this.

**Closed** 2018-02-28 12:26 UTC
