### ISSUE TITLE
Windows Touch Support

### ISSUE THREAD

**Issue by nille02** [canton7/SyncTrayzor#293] opened 2016-07-12 14:56 UTC
Currently, if you try to scroll in synctrayzor with you touchscreen, you mark the text instead of scrolling.

**Comment by canton7** [comment] 2016-07-12 15:12
Duplicate of #286, #241, (and see also #129). 

The bottom line is that the embedded browser doesn't support touch scrolling, so there's nothing I can do.

**Closed by canton7** 2016-07-12 15:12 UTC
