### ISSUE TITLE
SyncTrayzor Stopped Working - System.NullReferenceException

### ISSUE THREAD

**Issue by jebeld17** [canton7/SyncTrayzor#412] opened 2017-10-02 00:32 UTC
Source
SyncTrayzor

Summary
Stopped working

Date
‎10/‎1/‎2017 9:26 AM

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\SyncTrayzor\SyncTrayzor.exe

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	SyncTrayzor.exe
Problem Signature 02:	1.1.18.0
Problem Signature 03:	59ad9b0f
Problem Signature 04:	SyncTrayzor
Problem Signature 05:	1.1.18.0
Problem Signature 06:	59ad9b0f
Problem Signature 07:	9e8
Problem Signature 08:	0
Problem Signature 09:	System.NullReferenceException
OS Version:	10.0.16299.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	ddbd
Additional Information 2:	ddbd215ad37399b9a4a1cf97329d4df3
Additional Information 3:	8777
Additional Information 4:	877777a7f505ed603abf6085b2f54255

Extra information about the problem
Bucket ID:	5a13c4f8e390316081277dc763375e0d (129551219748)

[ReliabilityHistory.zip](https://github.com/canton7/SyncTrayzor/files/1347666/ReliabilityHistory.zip)
[msinfo32_export.txt](https://github.com/canton7/SyncTrayzor/files/1347667/msinfo32_export.txt)

**Comment by canton7** [comment] 2017-10-02 11:40
I need the message which SyncTrayzor shows in its "Something went wrong" window. Failing that, I need the information which is printed to its log file (go to File -> Settings -> Logging + STTRACE -> Show SyncTrayzor Log File)

**Comment by jebeld17** [comment] 2017-10-04 09:49
I'll get this when I can :-)
It's very early in the AM here right now, and I'm sorry I didn't see this before.

**Comment by jebeld17** [comment] 2017-10-04 09:53
PS: I think this issue may be unique to Windows 10 v1709, the Fall Creators Update. I have two PCs now running 1709, with both PCs now crashing not very long after opening Synctrayzor.
Please note v1709 is now in RTM, so this issue should not be treated differently from the current public builds of Windows. (RTM releases are considered stable enough by Microsoft to preinstall onto PCs)

**Comment by jebeld17** [comment] 2017-10-04 10:05
[syncthing.log](https://github.com/canton7/SyncTrayzor/files/1355381/syncthing.log)
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/1355382/SyncTrayzor.log)

**Comment by canton7** [comment] 2017-10-04 11:31
The problem is that your configuration file is corrupt. Then there's a race where we try and report this corruption while trying to do something else, which results in the nice error message that would normally be shown not being shown after all.

Can you post `C:\Users\jebel\AppData\Roaming\SyncTrayzor\config.xml `?

**Comment by canton7** [comment] 2017-10-04 11:31
Hmm your Syncthing log file has the same problem - a bunch of NULL bytes in the middle. I think you've probably got a failing disk.

**Comment by jebeld17** [comment] 2017-10-08 07:50
Hey, I just read your message.

I actually beg to differ, but I did back up my information just in case.

The reason behind why I'm begging to differ is because this is happening on not only one PC, but two completely different PCs running completely different internal components, on the same version of Windows, 10 v1709 (RTM).

**Comment by canton7** [comment] 2017-10-08 08:49
Something is writing lots of null bytes into various files. This is not a problem with SyncTrayzor.

**Comment by jebeld17** [comment] 2017-10-09 02:45
The only problem I can think it's related to is the upgrade to 1709 RTM. Even then, that is still causing issues with Syncthing and Synctrayzor somehow. Also, a patch can be sent to fix Syncthing and Synctrayzor much easier than Windows 10.

**Comment by jebeld17** [comment] 2017-10-09 02:47
Is there anything you'd recommend me do to help diagnose this further? Maybe the old logs can be either removed after manually going in and making sure my files are okay, and send the new logs created from that point out?

**Comment by canton7** [comment] 2017-10-09 06:45
No, nothing can be done to fix SyncTrayzor or Syncthing, because there is nothing to fix. Something (your OS, driver, disk, etc) is failing to write files correctly OR some other application, OS, drivers, disk, etc, is overwriting parts of files with null bytes OR your disk is failing to read back files correctly. You haven't posted your config as requested, which may give a clue as to which of these cases were looking at. Asking for a fix in SyncTrayzor is like driving a car over a bridge which has collapsed, then asking for the car to be fixed.

**Comment by jebeld17** [comment] 2017-10-09 15:37
Sorry, I forgot to. My config keeps rewriting itself anyways since I need to keep deleting it.
Let me grab the Config.

**Comment by jebeld17** [comment] 2017-10-09 15:39
[config-desktop.zip](https://github.com/canton7/SyncTrayzor/files/1369067/config-desktop.zip)

**Comment by jebeld17** [comment] 2017-10-09 15:45
[Config-Laptop.zip](https://github.com/canton7/SyncTrayzor/files/1369085/Config-Laptop.zip)

**Comment by canton7** [comment] 2017-10-09 15:55
OK, a bunch of the files in Config-Laptop/old/old are just varying numbers of null bytes, nothing more. There's nothing I can do or say here - something's either not writing the file to disk properly, or it's getting overwritten after I'm writing it.

**Comment by jebeld17** [comment] 2017-10-09 18:11
I just started getting the same System.NullReferenceException error in a completely different app (Bulk Crap Uninstaller, https://klocmansoftware.weebly.com/).

I am pretty sure this deals directly with an error inside 1709 RTM. I'll report this to Microsoft manually and send you the link when I am done, in case you have any better info than I do to provide to Microsoft. :-)


PS: See the attached .ZIP with the auto-generated bug report information made by Bulk Crap Uninstaller when I got the same error. I am pretty sure you can help diagnose this better than I can! :-)

**Comment by canton7** [comment] 2017-10-09 18:14
That is something completely unrelated. 

A Null Reference Exception is an incredibly common thing. It's normally a programmer error. I'm afraid I'm not going to spend my free time looking into a random issue in an application I've never even heard of before.

**Comment by jebeld17** [comment] 2017-10-09 18:16
I wasn't sure if this was related, and I don't have the knowledge you have when it comes to these issues.
Sorry.
Thank you though.

I'll report anything else I can directly link to SyncTrayzor on here when I can, though.

**Comment by canton7** [comment] 2017-11-27 13:06
Closing as I can't fix disk corruption.

**Closed by canton7** 2017-11-27 13:06 UTC
