### ISSUE TITLE
SyncTrayzor eating up RAM

### ISSUE THREAD

**Issue by sluTTYusr** [canton7/SyncTrayzor#37] opened 2015-03-23 18:32 UTC
SyncTrayzor.exe is using almost half a GB of RAM... 438.196 K precisely.
I saw this https://github.com/canton7/SyncTrayzor/issues/3 however I think this is not the same issue because it obviously is not solved and 90 MB are far far away. 
This is on Windows 7 x64.
Just updated to the latest build, same issue.

**Comment by canton7** [comment] 2015-03-23 18:47
1. What sort of memory? Private working set? Working set? Private? These have significantly different meanings.
2. Is SyncTrayzor closed to the tray, of restored from tray? Does closing to tray / restoring from tray make a difference?
3. How long has SyncTrayzor been running? Does it consume that much on start-up? Only after a few hours? Only after repeating some operation?

Please also run SyncTrayzor for > 30 mins, then grab the log file (in `C:\Users\<You>\AppData\Roaming\SyncTrayzor\logs\SyncTrayzor.log`) and paste it in here, or stick it on http://gist.github.com and link it into here. SyncTrayzor captures memory statistics, but only every 30 mins (I should really reduce that...)

Thanks

**Comment by sluTTYusr** [comment] 2015-03-23 19:12
I am running the portable Version if it matters...

1. Here is a screen shot from the resource manager:
![2015-03-23_195632](https://cloud.githubusercontent.com/assets/11618119/6788163/fdc42cda-d197-11e4-843b-43e87b11521e.png)

2. It's been open, closed to tray and restored from tray... makes no significant difference, memory usage is always >400MB

3. It's takes up around 430MB right from the start without any user interaction and only one directory which is in sync.

Here is the log: https://gist.github.com/sluTTYusr/1d804c5f9ab0f62e990e#file-synctrayzor-log
It's quite long because I synced the pictures from my phone.

**Comment by canton7** [comment] 2015-03-23 19:32
Being portable shouldn't make any difference, other than the location of the log file.

OK, so it's 400mgs of private working set - that's pretty bad.

So you're saying you start SyncTrayzor, and straight away memory usage jumps up to 400MB? Can you try starting it with `-minimized` (i,e, `SyncTrayzor.exe -minimize`), and check the memory usage? There's a bunch of stuff that's not loaded until the first time that SyncTrayzor is restored from the tray.

Looking at the log, it looks like the embedded browser might be responsible for that memory usage, in which case I'd expect there to be very low memory usage at first if you start with `-minimized`.

**Comment by sluTTYusr** [comment] 2015-03-23 20:04
I can confirm that when starting minimized SyncTrayzor only takes up about 25 MB of private working set memory.
Once I call the main window from the tray it surges up to >400MB immediately and does not decrease when I close it to tray again.

**Comment by canton7** [comment] 2015-03-23 20:41
OK, so it's almost certainly the embedded browser component (CefSharp) - a call to `Cef.Initialize()` is probably to blame. I just have no idea why it's chosen you to screw over - I've never seen it do that on anyone else's computer.

If you're got some spare time, I'd be very grateful if you could do a bit of profiling for me (I'll give more detailed instructions if you have got the time). Otherwise, I'll do some issue reading.

Is there anything "special" about this computer, at all? Anything which sticks out?

**Comment by sluTTYusr** [comment] 2015-03-24 06:28
Sure... let me know what info you need.
The PC is not special at all... Z68 chipset, 16GB of memory, Intel Core i7-2600K.

**Comment by canton7** [comment] 2015-03-24 08:15
Great, thank you! I'm going to spend a little while playing with CEF's debug capabilities, see what I can get out of them: I may send you a special build in a few days and ask you to run it. If I can't get anything useful out of that, the only thing to do may be to attach a profile on your machine and grab some screenshots.

**Comment by canton7** [comment] 2015-03-24 12:21
Righty, I've created a build which enables CEF's remote debugging functionality, on port 2004. This may show us something interesting, or it may not. It's worth a check, at any rate!

Instructions:

1. Download https://s3-eu-west-1.amazonaws.com/canton7/SyncTrayzorPortable-cefdebug-x64.zip
2. Unzip, run, start Syncthing
3. Open Chrome (it does have to be chrome), and point it at `localhost:2004`. 
4. You should see a single link called 'Syncthing | YOURCOMPUTERNAME'. Click it.
5. You'll now have chrome dev tools pointed at CEF, which is pretty cool.
6. Click 'Profiles' at the top, then 'Take Heap Snapshot' and 'Take Snapshot'
![snapshot](https://cloud.githubusercontent.com/assets/568104/6801465/d5f6ee08-d21f-11e4-93c3-4fba79509a5d.png)
7. See what it gives you. Mine looks a bit like this:
![snapshot2](https://cloud.githubusercontent.com/assets/568104/6801492/171ac1ac-d220-11e4-9bcc-e5a6bfdc4d24.png)
I'd be very interested to see if yours is significantly different. If it is, then we can start investigating. If it isn't, then it's likely that the memory is being used by CefSharp, and not CEF itself. In that case, we'll have try another approach.

FYI, the download I linked you to is the portable x64 version of https://github.com/canton7/SyncTrayzor/commit/81b72219fc7e528ed84c1692e09e2134fb2041c9, with CefRemoteDebuggingPort set to 2004 in SyncTrayzor.exe.config.

Thanks!

**Comment by canton7** [comment] 2015-03-24 13:22
@Rewt0r - can you take a look at this and see if it matches what you were seeing a while back, please?

**Comment by sluTTYusr** [comment] 2015-03-24 14:30
Here is the output of the heap snapshot, seems to be similar to yours:
![2015-03-24_152633](https://cloud.githubusercontent.com/assets/11618119/6803854/9ee46e52-d23a-11e4-8759-8cc869021b6f.png)

... and the corresponding row from taskmanager:
![2015-03-24_152659](https://cloud.githubusercontent.com/assets/11618119/6803866/b4085960-d23a-11e4-943b-9cdad10be120.png)

**Comment by canton7** [comment] 2015-03-24 14:52
Ok, so that means the memory usage most likely isn't inside CEF itself, but in CefSharp - the C# adapter. That means we'll have to use a C# profiler to dig them out.

Now, they it might be managed memory, in which case most profilers can figure it out, or unmanaged, in which case there's only 1 profiler that I know of which can help... Let's start with the free ones though :)

Could you please:
1. Download the [CLR Profiler](http://clrprofiler.codeplex.com/downloads/get/532810). it's free and doesn't require any installation.
2. Unzip and run `64/CLRProfiler.exe`
3. Make sure 'Profiling active', 'Allocations', and 'Calls' are checked
4. Click 'Start Desktop App'. Navigate to `SyncTrayzor.exe`. 
5. Let it start SyncTrayzor. Make sure Syncthing is running, and that high memory usage is reported in task manager.
6. Click on 'Show Heap now'
7. Use your judgement. Big blocks = lots of memory. You can double-click stuff to view it in more detail. I'd appreciate screenshots / text dumps of anything that looks remotely interesting - Edit -> Copy as text to clipboard will copy everything if nothing's selected, or the selected node if you've selected one. Here's a top-level view of what I see:
![profile](https://cloud.githubusercontent.com/assets/568104/6804330/0cd41436-d235-11e4-9b36-24ac2ba2664f.PNG)

Profiling is more art than science sometimes. Grab screenshots / dumps / whatever of the top-level stuff, then use common sense to look at interesting large stuff in detail. It might take a couple of rounds of "Look what I found" "Hey *that* node looks interesting, mind digging into it" in order to get to the bottom of things.

Thanks a lot for your help - without being able to reproduce this locally you're the only chance I have of finding the root cause of this! :smile:

**Comment by sluTTYusr** [comment] 2015-03-24 15:20
I am sorry but I don't see anything suspicious... but I am no developer... here's a screen shot...
I can scroll far to the right but the fat chunks are all in the upper left.
![2015-03-24_161219](https://cloud.githubusercontent.com/assets/11618119/6805079/70c304f0-d241-11e4-9a7d-7acd8370e19b.png)

Memory usage went to 1.3GB while running CLR Profiler and did not decrease after closing it.
![2015-03-24_160644](https://cloud.githubusercontent.com/assets/11618119/6805115/9701f108-d241-11e4-9df3-ee6a3b87ccb0.png)

**Comment by canton7** [comment] 2015-03-24 15:33
Thanks for looking at this!

Ah, 6.6MB at root. That means that leak is likely in unmanaged memory, which the CLR Profiler can't access. I'll do some research into the best way to dig into this and get back to you - I know one profiler which can do it, but it only comes with a trial.

I'd expect the profiler to cause memory consumption to increase: that's pretty normal.

**Comment by canton7** [comment] 2015-03-24 15:51
Would you mind testing this build: https://s3-eu-west-1.amazonaws.com/canton7/SyncTrayzorPortable-x64-cefdebug2.zip ?

I've upgraded CefSharp to the bleeding edge - there have been a couple of memory-related commits, and we should make sure they haven't fixed the issue. Thanks!

**Comment by sluTTYusr** [comment] 2015-03-24 16:00
Thank you for all the effort.
The last build did not change anything... still >400MB memory consumption.
I tried the latest official biuld in an VM with Windows 8 x64 and it does not seem to leak.
What else can I do to help?

**Comment by canton7** [comment] 2015-03-24 16:12
OK, that's good to know, thanks.

I think this is going to have to go upstream to CefSharp, so anything information we can grab would help them. Give me a day or so, and I'll put together some instructions for getting a dump from a more complex profiler.

Thanks for your wilingness to help here! I really appreciate it.

**Comment by canton7** [comment] 2015-03-24 16:14
There must be *something* either in your environment or possibly hardware which is causing this... Is chrome installed on your machine but not in the VM, maybe?

**Comment by sluTTYusr** [comment] 2015-03-24 16:20
Hmmm... I have Google Chrome installed on both the real PC and the VM. 
On the physical PC I have Chromium installed in addition to get rid of the Google prying eyes.
This could not possibly be the reason... right?

**Comment by canton7** [comment] 2015-03-24 16:23
It might be... Would you mind testing it for me?

It might be easier to install Chromium (with the same config) in your VM, than go through the backup / uninstall / test / reinstall cycle on your real PC.

**Comment by canton7** [comment] 2015-03-24 16:41
Something else to try...

Could you donwload https://s3-eu-west-1.amazonaws.com/canton7/gacutil.zip, extract, and run `gacutil.exe -l > output.exe` on your real PC, then post output.txt somewhere?

**Comment by canton7** [comment] 2015-03-24 16:42
Also, where did you download Chromium from? I know there are several places, which might install in different ways... I want to see whether I can replicate this locally.

**Comment by sluTTYusr** [comment] 2015-03-24 16:47
Here is the output from gacutil.exe: http://pastebin.com/qqRRJSkR

I installed Chromium in the VM with the exact expansions/settings as on the PC. This did not make a difference for the memory usage of SyncTrayzor.

**Comment by canton7** [comment] 2015-03-24 17:03
Thanks for checking those. I can't see CEF in the GAC, which is what I was hoping for.

Could you please run the same gacutil comand in the VM, and pastebin the results? Maybe there's some significant difference between them...

**Comment by sluTTYusr** [comment] 2015-03-24 17:10
Here is the output from the VM: http://pastebin.com/2xxbnsZz

**Comment by canton7** [comment] 2015-03-24 17:39
Thanks! Unfortuntaly there's nothing obvious....

Can you try this build: https://s3-eu-west-1.amazonaws.com/canton7/SyncTrayzorPortable-x64-cefdebug3.zip please? There should also be a `debug.log` file in the same folder as `SyncTrayzor.exe` once you've run it. Could you pastebin that?

I've disabled GPU rendering (this was suggested as a reasonable step to take, and that *is* one significant difference between a real PC and a VM. I also cranked up CEF's logging, hence debug.log.

**Comment by sluTTYusr** [comment] 2015-03-24 17:49
Here it is: http://pastebin.com/pf1eB0qc

First, I started it with 'SyncTrayzor.exe' and let it runa couple of minutes the I killed it and started it again with '-minimized'. It only added to the debug log after I opened the main window.

**Comment by canton7** [comment] 2015-03-24 17:50
Thanks. Yeah, we only start Cef once it's restored from the tray. Was the memory usage still high with that build?

**Comment by sluTTYusr** [comment] 2015-03-24 17:51
Yes it was. 
Not when I started with '-minimized' though.

**Comment by canton7** [comment] 2015-03-24 17:52
Yeah - that'll be the same as it always was. We only start Cef when SyncTrayzor is first restored from the tray. Memory usage only increases when we start Cef.

**Comment by sluTTYusr** [comment] 2015-03-24 18:56
I just realized I overlooked your question regarding Chromium...
I downloaded the 'Chromium Package' from here: http://chromium.woolyss.com/
The link is in the second, reddish box.
It installs to C:\Program Files (x86)\Chromium

**Comment by Rewt0r** [comment] 2015-03-24 20:10
Glad to see you're starting to get to the bottom of it! Apologies for my delayed response @canton7, I've been busy investigating an issue with a program being able to bypass UAC and infect a machine! A bit coincidental that we've been talking about this recently.

**Comment by canton7** [comment] 2015-03-24 20:33
@sluTTYusr aha, thanks for that. I'll try replicating tomorrow. I'll also put together a little dummy application which should replicate the problem and not much more - once we've confirmed that that still exhibits the issue, I'll push it up to the CefSharp guys.

@Rewt0r are the symptoms we're seeing similar to the ones you saw? I know different people reported different memory usage patterns, and wasn't sure whether your experiences matched those being described here.

**Comment by canton7** [comment] 2015-03-25 08:31
Another day, another couple of new things to try...

Firstly, could you try downloading and running the 32-bit version? *Just* in case that affects anything...

Secondly, could you please:
1. Download https://s3-eu-west-1.amazonaws.com/canton7/CefSandbox.zip
2. Unzip, and run CefSandbox.exe
3. Check its memory usage: it should be pretty low
4. Click 'Initialize'
5. Check its memory usage: it should now be very high
6. Click 'Shutdown'
7. Check the memory usage again: it should be low

Note that doing anything other than starting the program, clicking Initialize, clicking Shutdown, closing the problem will cause a crash. Clicking Initialize twice, Shutdown twice, Shutdown before Initialize, Initialize after Shutdown, etc, will all cause crashes.

Thanks a lot!

**Comment by sluTTYusr** [comment] 2015-03-25 08:42
Good morning.
The x86 version uses less memory than the x64 version but still >290 MB
![2015-03-25_093649](https://cloud.githubusercontent.com/assets/11618119/6820837/ce2d4dc6-d2d2-11e4-891b-3ba4cdec7af9.png)

Right after starting, CefSandbox.exe uses 18MB of private working set memory.
After clicking 'initialize' memory usage increases to 406MB.
A click on 'shutdown' triggers a decrease to 38MB.
I clicked 'initialize' again > CefSandbox crashes.

**Comment by canton7** [comment] 2015-03-25 09:15
Fantastic! The fact that the 32-bit memory usage is roughly half of the 64-bit memory usage is potentially significant. The crash on 'initialize' again is expected - thanks for testing that :smile: 

I think I've got enough to open an issue at CeSharp now... Let's see what happens.

**Comment by canton7** [comment] 2015-03-25 09:25
Righty, CefSharp/cefSharp#902 is open. Let's see what happens.

**Comment by sluTTYusr** [comment] 2015-03-25 09:27
Great. Just let me know if you or they need any more info from my PC.

**Comment by canton7** [comment] 2015-03-25 09:28
Thank you! I can't tell you how much I appreciate the time and willingness you're putting into this - I wouldn't stand a chance at debugging this without it :smiley:

**Comment by Rewt0r** [comment] 2015-03-25 11:13
@canton7 my usage never went as high as this. I haven't had it open for a while but I'm sure it never went over 200MB.

**Comment by canton7** [comment] 2015-03-25 11:21
@Rewt0r are you running 32-bit or 64-bit?

**Comment by canton7** [comment] 2015-03-25 12:15
@sluTTYusr do you run Steam? Skype? Anything else on this list: http://en.wikipedia.org/wiki/Chromium_Embedded_Framework#Applications_using_CEF ?

If so, do they use an awful amount of memory?

**Comment by sluTTYusr** [comment] 2015-03-25 12:20
I don't run Steam. I have Skype installed but it's not running all the time. Just started it to see how the memory consumption is: about 100MB. Don't know if that's too much.

**Comment by canton7** [comment] 2015-03-25 12:22
I think I was mistaken about Skype using CEF internally - bad memory. Can you confirm whether you're running any of the other programs listed in the link above?

**Comment by sluTTYusr** [comment] 2015-03-25 12:23
No, nothing else from the list.

**Comment by canton7** [comment] 2015-03-25 13:52
OK thanks. All of the things on the list also use CEF, and I was interested in whether they might also take huge amounts of memory. If they did, then I don't think there's a lot of hope for us.

I'm leaning towards rewriting the UI in C# now anyway - it shouldn't be too much effort (most of the data model is already in place). Maybe 3 weeks? That'll halve the memory usage for everyone (and significantly reduce it for you!)

**Comment by sluTTYusr** [comment] 2015-03-25 14:01
I could simply install the Steam Client to verify, ok?
Sorry I could not be of more help.
It seems I am the only one having this issue anyway... which is hard to believe actually... probably the only one who noticed and came forward.

**Comment by canton7** [comment] 2015-03-25 14:08
You've gone above and beyond your duty as a user in helper here, don't worry!

There have been a few other complaints of high memory usage, but no-one stuck around long enough to help me dig into it. 

If you have the spare time, please pick any appilcation from that wikipedia list and give it a shot. Steam will probably require you to log in, but others might not.

**Comment by sluTTYusr** [comment] 2015-03-25 15:08
I had to unlock my old BattleNet account and update the client.
Now it is using about 100MB of private set memory. Don't know if that's too much.

**Comment by canton7** [comment] 2015-03-25 15:30
Hah, thanks for doing that! Hrm, it's much less than 400MB, which is what I was look for. Although... Is it 32-bit (if you look in Task Manager, does the name of the exe have an asterisk next to it)?

**Comment by sluTTYusr** [comment] 2015-03-25 17:13
Yes BattleNet is a 32-bit application.
![2015-03-25_181238](https://cloud.githubusercontent.com/assets/11618119/6830530/92e143ce-d31a-11e4-9c02-a1e15ace8f5c.png)

**Comment by canton7** [comment] 2015-03-25 17:29
Hmmmm it's still using too little for Cef to be having the same issue as we're seeing here. Maybe it's old and using an old version of Cef? Hard to tell....

**Comment by canton7** [comment] 2015-04-02 08:20
Righty, the plan is to create a native UI (not relying on CEF). That will provide an alternative for people with CEF problems

**Comment by canton7** [comment] 2016-01-22 17:44
I haven't had anyone mention anything since April-ish.

**Closed by canton7** 2016-01-22 17:44 UTC
Labels: future

**Comment by sluTTYusr** [comment] 2016-01-25 17:01
Just saw this has been closed...
installed version 1.1.2 just to check... SyncTrayzor.exe uses ~ 176MB of private working set memory... down from >400MB... still a lot. 
What's considered a normal amount of mem usage?

**Comment by canton7** [comment] 2016-01-25 17:30
I expect less than 60MB when SyncTrayzor is minimized to the tray, and less than 100MB (normally < 70MB) when in the foreground.

If you're seeing usage above this, I'm afraid it's down to the embedded browser component I use: there's nothing I can do myself. The next version will include an updated version of the embedded browser, which may (?) help you.

**Comment by canton7** [comment] 2016-01-25 17:32
(You can grab an intermediate build, with the updated browser component, here: https://ci.appveyor.com/project/canton7/synctrayzor/build/artifacts)

**Comment by sluTTYusr** [comment] 2016-01-25 17:41
Thanks. Just tried the portable version of the intermediate build.
It's still >170MB. Minimized or foreground does not make a difference.

**Comment by canton7** [comment] 2016-01-26 09:13
I don't think there's anything I can suggest or do then, sorry.

CEF is taking up a lot of memory, in seemingly very particular circumstances. That's not something that I can control, and given that CEF is massive project with loads of complexity, I'm not sure it's something I'd be able to get to the bottom of given limitless time and money. 

Since I haven't heard anyone mention anything to do with memory usage in over 9 months, I assume that either this issue only affects a very small people, or it does affect more people but they don't care.

Sorry.

**Comment by Billiam** [comment] 2016-02-10 17:51
Would it be possible to support a version of trayzor without the embedded browser? 

I'm currently using trayzor for its tray icon/notification, preferences, etc. but am happy to use a system browser to view the syncthing status page.

**Comment by canton7** [comment] 2016-02-10 17:56
If you start SyncTrayzor in the tray, and do not restore it from the tray, then it does not initialise the embedded browser. That's as much as I can do without creating a separate build which entirely excludes the embedded browser libraries.

I'm not prepared to create 4 new builds which ship without the embedded browser at all: that's a huge amount of additional effort and maintenance, will add confusion to newbies trying to decide what to download (and picking the wrong thing, and calling SyncTrayzor as a whole shit as a result), for a very small minority of users.

**Comment by temporarium** [comment] 2016-12-22 22:13
I know this is "old", but I've had over 500Kb of RAM being used over the last few SyncTrayzor versions (ever since I remember). Windows 7x64, SyncTrayzor portable, doesn't matter if minimized or not...

Are there any solutions? Thanks!

**Comment by canton7** [comment] 2016-12-23 08:33
500kb is nothing - did you mean 500mb? 

I'm afraid it's something to do with the embedded chromium component, and I've never managed to find any factors which affect it other than sometimes taking a lot of memory on some machines.

**Comment by temporarium** [comment] 2016-12-23 21:20
You're too kind :-) Of course, I meant 500mb...

I take it that that chromium component hasn't been updated since last year?

I only use a portable version of Iron (Chromium derivative), but I don't have Chromium or Chrome installed on the system. Could that be a clue?

I have Comodo firewall installed... I'm trying to think what else could be "special" about my setup...

I'm attaching a couple of screenshots.
![sshot-2](https://cloud.githubusercontent.com/assets/4754345/21462566/998b1444-c92b-11e6-81ed-aa73d5c18d63.jpg)
![sshot-1](https://cloud.githubusercontent.com/assets/4754345/21462568/9ac653f0-c92b-11e6-89ad-160cf8072ce4.jpg)
