### ISSUE TITLE
Synctrayzor 1.1.22 doesn't work after downloading and configuring Syncthing 1.0.1 first

### ISSUE THREAD

**Issue by caspark** [canton7/SyncTrayzor#502] opened 2019-02-19 04:14 UTC
# Repro

1. Download https://github.com/syncthing/syncthing/releases/download/v1.0.1/syncthing-windows-amd64-v1.0.1.zip , extract it, and configure it (I set up one shared folder with my phone).
2. `choco install synctrayzor` (which installed 1.1.22 for me)
3. Launch synctrayzor

# Observed

The log messages in the bottom pane of the window say
```
[ARRLV] 20:04:36 INFO: syncthing v0.14.51 "Dysprosium Dragonfly" (go1.11 windows-amd64) teamcity@build.syncthing.net 2018-09-24 12:50:31 UTC
[ARRLV] 20:04:36 INFO: My ID: ARRLVGV
[ARRLV] 20:04:37 INFO: Single thread SHA256 performance is 497 MB/s using minio/sha256-simd (445 MB/s using crypto/sha256).
[ARRLV] 20:04:38 INFO: Hashing performance is 416.61 MB/s
[ARRLV] 20:04:38 FATAL: Error opening database: Syncthing v0.14.53 required
```
This repeats several times until synctrayzor pops open an error dialog.

# Expected

No error message and synctrayzor works with the configuration from the previously downloaded syncthing.

# Notes

* Maybe the bundled syncthing is out of date?
* Possibly related to #493 ?

**Comment by canton7** [comment] 2019-02-19 20:21
Yep, dupe of #493

**Closed by canton7** 2019-02-19 20:21 UTC
