### ISSUE TITLE
Invalid Operation Exception

### ISSUE THREAD

**Issue by dsvf** [canton7/SyncTrayzor#91] opened 2015-05-19 22:16 UTC
Synctrayzor 1.0.18 x64, same error with Synctrayzor 1.0.16 x64. OS is Windows 7 Professional 64 bit.

What happens: Start Synctrayzor, Error message pops up. No other windows or messages appear before that.

The following error message is given:

```
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Exception: -1, -1 is not a valid value for Int32. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Drawing.PointConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at SyncTrayzor.Services.Config.WindowPlacement.ReadXml(XmlReader reader) in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\Config\WindowPlacement.cs:line 41
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfiguration.Read3_Configuration(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderConfiguration.Read4_Configuration()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at SyncTrayzor.Services.Config.ConfigurationProvider.LoadFromDisk(Configuration defaultConfiguration) in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 153
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 85
   at SyncTrayzor.Bootstrapper.Configure() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Bootstrapper.cs:line 85
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment] 2015-05-20 07:10
Mind posting your SyncTrayzor config file? You'll find it at `C:\Users\<You>\AppData\Roaming\SyncTrayzor\config.xml`. Something in that config file has been corrupted, or something like that.

As a short-term fix you can rename that config file and restart SyncTrayzor (although you will lose SyncTrayzor-specific settings).

**Comment by dsvf** [comment] 2015-05-20 08:58
<?xml version="1.0"?>
<Configuration xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="3">
  <ShowTrayIconOnlyOnClose>false</ShowTrayIconOnlyOnClose>
  <MinimizeToTray>false</MinimizeToTray>
  <CloseToTray>true</CloseToTray>
  <ShowSynchronizedBalloon>true</ShowSynchronizedBalloon>
  <ShowDeviceConnectivityBalloons>true</ShowDeviceConnectivityBalloons>
  <SyncthingAddress>localhost:8384</SyncthingAddress>
  <StartSyncthingAutomatically>true</StartSyncthingAutomatically>
  <SyncthingApiKey>Nqzfyi-opfXBCAu6Nad79N5WO13u0iqKfUM1eik1</SyncthingApiKey>
  <SyncthingEnvironmentalVariables />
  <SyncthingUseCustomHome>false</SyncthingUseCustomHome>
  <SyncthingDenyUpgrade>false</SyncthingDenyUpgrade>
  <SyncthingRunLowPriority>false</SyncthingRunLowPriority>
  <Folders />
  <NotifyOfNewVersions>true</NotifyOfNewVersions>
  <ObfuscateDeviceIDs>true</ObfuscateDeviceIDs>
  <UseComputerCulture>true</UseComputerCulture>
  <SyncthingConsoleHeight>100</SyncthingConsoleHeight>
  <WindowPlacement>
    <IsMaximised>false</IsMaximised>
    <MinPosition>-1, -1</MinPosition>
    <MaxPosition>-1, -1</MaxPosition>
    <NormalPosition>653, 121, 1100, 700</NormalPosition>
  </WindowPlacement>
  <SyncthingWebBrowserZoomLevel>0</SyncthingWebBrowserZoomLevel>
  <LastSeenInstallCount>0</LastSeenInstallCount>
</Configuration>

**Comment by canton7** [comment] 2015-05-20 09:13
Aah bollocks. What country are you in? Specifically, in "Region and Language" (in Control Panel), which language is selected under "Format"?

**Comment by dsvf** [comment] 2015-05-20 09:24
"Format" is German (Germany)
System language is English

**Comment by canton7** [comment] 2015-05-20 09:30
So a language which uses ';' as its item separator. That fits. I have other German users: I wonder why none of them saw this issue...

Did you copy that config file from another computer? Or change the "Fomat" setting?

**Comment by dsvf** [comment] 2015-05-20 09:33
Changing the "Format" is possible. This is a new install of windows 7 (English), the format change to German might have happened after installing SyncTrayzor.

**Comment by canton7** [comment] 2015-05-20 09:37
Yeah, that's probably the cause, and would explain it.

Edit the config file, and replace every comma with a semicolon in the `<MinPosition>`, `<MaxPosition>`, and `<NormalPosition>` tags

**Comment by dsvf** [comment] 2015-05-20 09:42
Well, it was only a blank file (I was not able to run SyncTrayzor, so could not modify any settings), so I did what you said previously and renamed the old config file.

Everything works now, so thanks for the fast support! Reverting to the "ugly console window" and losing folder watching would have been gravely annoying!

**Comment by canton7** [comment] 2015-05-20 09:43
Sweet! I meant edit the config file with a text editor, but letting it be regenerated is fine too.

(Re-opening, as my process is to close issues once a fix has been released)

**Closed** 2015-05-27 11:56 UTC
Labels: fix-scheduled
