### ISSUE TITLE
Clicking tray icon once after autostartup invokes main WebUI

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#277] opened 2016-06-07 19:26 UTC
As the title says:

If SyncTrazor is set to "automatically start on login", after the boot, click the tray icon once:

Result: both the "tray info bubble" and the main WebUI are opened.

Expected result: single click shows only the "tray info bubble", double click opens WebUI.
(after closing the WebUI window, subsequent clicks behave properly.)

**Comment by scienmind** [comment] 2016-06-07 19:40
Update:
Actually it happens also after sync has occurred, and icon has refreshed. 
Click it once - all windows pop up

**Comment by canton7** [comment] 2016-06-07 19:53
Version?

**Comment by scienmind** [comment] 2016-06-07 20:01
> Version?

Current stable: 1.1.10

I'll test the scheduled fix for #270, maybe the updated icon library will do the trick here as well...

**Comment by scienmind** [comment] 2016-06-07 20:08
Nope, unfortunately the fix for #270 doesn't fix this one.

It seems like the first interaction with the icon after (icon's) refresh is not processed properly... Are you sure it's not in SyncTrayzor territory?

**Comment by canton7** [comment] 2016-06-07 20:11
Yes I'm sure. 

I tell the icon "when you're single-clicked, do this. When you're double-clicked, do that".

**Comment by canton7** [comment] 2016-06-07 20:12
Patches welcome, otherwise without a way to reproduce it I've got nothing to start with.

**Comment by canton7** [comment] 2016-06-07 20:17
Try turning odd the icon animation, see if that changes anyrhing.

**Comment by scienmind** [comment] 2016-06-07 20:23
Nope, the behavior remains the same, the icon refresh still occurs every sync (even if not animated), so the behavior is not different

**Comment by scienmind** [comment] 2016-06-07 20:34
Remark: Single right click has the same effect after refresh.

**Comment by canton7** [comment] 2016-06-07 21:14
>  the icon refresh still occurs every sync (even if not animated)

What do you mean? What refresh?

**Comment by canton7** [comment] 2016-06-07 21:18
> Remark: Single right click has the same effect after refresh.

Right, the right-click is entirely, 100% handled by the library. I literally have no code which is invoked when someone right-clicks the icon: the menu is shown by the library.

**Comment by scienmind** [comment] 2016-06-07 21:34
> What do you mean? What refresh?

I mean the icon's refresh. Every time sync occur, the icon is refreshed/redrawn
On Win10 it is easily noticeable: if you move the icon to the "hidden" area (you need to "expand" the tray area to see all the hidden icons), then after "refresh" it is "unhidden" and showing up, until user have some interaction with the tray area, then it'd be hidden again.
This refresh->unhide behavior is not rare in Win10, it can be observed with many programs (dropbox does the same, etc.)

I hope my mumbling makes some sense...

**Comment by canton7** [comment] 2016-06-07 21:49
Not really. There's literally no code to do anything with the icon when syncing finishes if you turn off animation. 

Is this just downloading a file, or uploading one too? 

Di you have the finished syncing notifications turned on?

**Comment by scienmind** [comment] 2016-06-22 21:29
> Is this just downloading a file, or uploading one too?

Only when downloading 

> Di you have the finished syncing notifications turned on?

Here's the config:
![capture](https://cloud.githubusercontent.com/assets/11633330/16284329/53058050-38d9-11e6-9539-6a575b7446fd.PNG)
(another machine has "Animate tray icon:" set to "Synchronizing", same behavior)

**Comment by canton7** [comment] 2017-03-19 21:40
Closing as I can't reproduce it, and noone else has reported it.

**Closed by canton7** 2017-03-19 21:40 UTC
