### ISSUE TITLE
Sync conflict shown - but there is no conflict

### ISSUE THREAD

**Issue by theincogtion** [canton7/SyncTrayzor#198] opened 2016-01-11 18:25 UTC
Pictures tell more than words:
![image](https://cloud.githubusercontent.com/assets/10852327/12242374/fc09e7ac-b898-11e5-9656-5e43b3264b23.png)

**Comment by canton7** [comment] 2016-01-12 09:24
You said you "restarted" and it didn't go away: what did you restart? Syncthing? SyncTrayzor?

**Comment by canton7** [comment] 2016-01-12 09:25
The Conflict Resolver window and the alerts bar use slightly different mechanisms to determine how many conflicted files there are. Both will do an exhaustive scan of your filesystem, but the alerts bar will use filesystem notifications to see when conflict files are added or removed, to avoid lots of scanning. It looks like it might be getting confused when loads of versions of a conflict are deleted at once.... I'll do some testing, try and reproduce.

**Comment by canton7** [comment] 2016-01-12 09:41
Looks like an evil little race: it's up to whether the visual tree gets fully constructed first, or I try and sort out the column headers. It looks like both might be happening at around about the same time...

**Comment by theincogtion** [comment] 2016-01-12 10:07
restart =  I restarted synctrayzor
After some hours the message seems to be away. I will confirm at today afternoon.

**Comment by canton7** [comment] 2016-01-12 10:15
> restart = I restarted synctrayzor

OK that's really odd. When you restart SyncTrayzor, it will do a full rescan for all conflicted files - exactly the same mechanism that's used when you open the conflict editor.

> After some hours the message seems to be away
That also shouldn't happen...

I'm confused. Let me have a bit more of a think, and dig more into your log file.

**Comment by canton7** [comment] 2016-01-12 10:33
Interesting: your log file doesn't actually show you resolving any conflicts. Did you use the Conflict Resolver UI to resolve conflicts at any point?

**Comment by theincogtion** [comment] 2016-01-12 11:44
I opened the conflict resolver to see the folders/files. I opened up the foldes and moves the files manually away,

**Comment by canton7** [comment] 2016-01-12 11:45
Aha right, that explains that.

**Comment by canton7** [comment] 2016-01-13 10:14
I didn't have quite enough logging in 1.1.1 to figure out what was going on.

Would you mind trying the intermediate build available here? https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.1.243/artifacts

I've made several changes to how conflict files are found and monitored, so you might not see the issue pop up again. If you do, the log file will contain more useful information.

Thanks!

**Comment by canton7** [comment] 2016-01-13 15:39
Quite a lot of fixing has happened in v1.1.2 - please reopen this if you can still reproduce it in v1.1.2. Thanks!

**Closed by canton7** 2016-01-13 15:39 UTC
