### ISSUE TITLE
Crash after wakeup

### ISSUE THREAD

**Issue by nof8** [canton7/SyncTrayzor#331] opened 2017-01-05 09:09 UTC
Version: 1.1.13.0; Variant: Portable; Arch: Amd64
Path: T:\PortableApps\synctrayzorportable-x64\synctrayzor.exe
```
System.Net.Http.HttpRequestException: Произошла ошибка при отправке запроса. ---> System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:8384
   в System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   в System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в SyncTrayzor.Syncthing.ApiClient.SyncthingHttpClientHandler.<SendAsync>d__2.MoveNext() в C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\ApiClient\SyncthingHttpClientHandler.cs:строка 21
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в RestEase.Implementation.Requester.<SendRequestAsync>d__18.MoveNext() в c:\projects\restease\src\RestEase\Implementation\Requester.cs:строка 283
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в RestEase.Implementation.Requester.<RequestVoidAsync>d__1f.MoveNext() в c:\projects\restease\src\RestEase\Implementation\Requester.cs:строка 312
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в SyncTrayzor.Syncthing.Devices.SyncthingDeviceManager.<PauseDeviceAsync>d__28.MoveNext() в C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Devices\SyncthingDeviceManager.cs:строка 141
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в SyncTrayzor.Services.Metering.MeteredNetworkManager.<UpdateDeviceAsync>d__33.MoveNext() в C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:строка 313
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в SyncTrayzor.Services.Metering.MeteredNetworkManager.<DeviceConnected>d__24.MoveNext() в C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:строка 179
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

[SyncTrayzor1.log.txt](https://github.com/canton7/SyncTrayzor/files/686835/SyncTrayzor1.log.txt)

**Comment by nof8** [comment] 2017-01-05 09:10
I've attached log, but it was inserted in the middle of dump somehow, the link is on line 5 or 6 in the message above

**Comment by canton7** [comment] 2017-01-05 09:13
Duplicate of #260, I think.

**Comment by canton7** [comment] 2017-02-10 15:00
Closing as duplicate

**Closed by canton7** 2017-02-10 15:00 UTC
Labels: duplicate
