### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by camsamzzyzx** [canton7/SyncTrayzor#349] opened 2017-03-13 16:53 UTC
```
Version: 1.1.13.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: File C:\IFS Backup\JBM-XPS-Docs\Outlook Files\Tomra.pst not found
File name: 'C:\IFS Backup\JBM-XPS-Docs\Outlook Files\Tomra.pst'
   at Pri.LongPath.Common.ThrowIOError(Int32 errorCode, String maybeFullPath)
   at Pri.LongPath.FileInfo.GetFileLength()
   at SyncTrayzor.Services.FilesystemProvider.GetFileSize(String path) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 92
   at SyncTrayzor.Services.Conflicts.ConflictFileManager.FindConflictsImpl(String basePath, IObserver`1 observer, CancellationToken cancellationToken) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Conflicts\ConflictFileManager.cs:line 186
   at SyncTrayzor.Services.Conflicts.ConflictFileManager.<>c__DisplayClass10_1.<FindConflicts>b__1() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Conflicts\ConflictFileManager.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Conflicts.ConflictFileWatcher.<ScanFoldersAsync>d__40.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Conflicts\ConflictFileWatcher.cs:line 242
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Conflicts.ConflictFileWatcher.<Reset>d__35.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Conflicts\ConflictFileWatcher.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment] 2017-03-13 16:59
Oh lovely, looks like the file vanished between us finding it, and trying to get some more details on.

I'm assuming this was a once-off, and you reproduce it?

**Comment by camsamzzyzx** [comment] 2017-03-13 18:02
I think so.  I've only seen this once and wouldn't know how to reproduce it.  As it happens, it's not a file I care about and only raised the issue because it asked me to.

**Comment by canton7** [comment] 2017-03-13 18:11
Cool. Thanks for reporting it: I'll get it fixed in the next version.

**Closed** 2017-03-30 19:50 UTC
Labels: fix-scheduled
