### ISSUE TITLE
Crash while minimised to tray

### ISSUE THREAD

**Issue by Rewt0r** [canton7/SyncTrayzor#115] opened 2015-06-18 11:25 UTC
2 machines today have closed with no warning.

Error from one:

```
Application: SyncTrayzor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
Stack:
   at Pri.LongPath.Path.Combine(System.String, System.String)
   at SyncTrayzor.Services.DirectoryWatcher.OnRenamed(System.Object, System.IO.RenamedEventArgs)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```

Version: 1.0.22.33

Error from the other:

```
Application: SyncTrayzor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Http.HttpRequestException
Stack:
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run()
   at SyncTrayzor.App.Main()
```

**Comment by canton7** [comment] 2015-06-18 11:36
The first crash dups #112.

What build was the second crash from?

**Comment by Rewt0r** [comment] 2015-06-18 11:37
Sorry, 1.0.18

**Comment by canton7** [comment] 2015-06-18 11:38
Can I see the log from the time of that second crash?

**Comment by Rewt0r** [comment] 2015-06-18 11:40
```
2015-06-18 05:39:07.5312 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 05:39:26.5652 [Warn] SyncTrayzor.Services.UpdateManagement.UpdateChecker: Fetching updates failed with an error System.Net.Http.HttpRequestException An error occurred while sending the request. Void ThrowForNonSuccess(System.Threading.Tasks.Task)    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Refit.RequestBuilderImplementation.<>c__DisplayClass28`1.<<buildCancellableTaskFuncForMethod>b__27>d__2a.MoveNext() in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient.<FetchUpdateAsync>d__0.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateNotificationClient.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateChecker.<FetchUpdateAsync>d__0.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateChecker.cs:line 82 System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'syncthing.antonymale.co.uk'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Refit.RequestBuilderImplementation.<>c__DisplayClass28`1.<<buildCancellableTaskFuncForMethod>b__27>d__2a.MoveNext() in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient.<FetchUpdateAsync>d__0.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateNotificationClient.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateChecker.<FetchUpdateAsync>d__0.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateChecker.cs:line 82
WebException The remote name could not be resolved: 'syncthing.antonymale.co.uk' System.Net.WebResponse EndGetResponse(System.IAsyncResult)
2015-06-18 05:44:07.5247 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 05:49:07.5390 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 05:54:07.5401 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 05:59:07.5428 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 06:04:07.5533 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 06:09:07.5598 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 06:14:07.5652 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 06:19:07.5667 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 06:24:07.5701 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 06:29:07.5716 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 06:34:07.5850 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 06:39:07.5864 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 06:44:07.5979 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 06:49:07.5993 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 06:54:07.6037 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 06:59:07.6122 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 07:04:07.6217 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 5MB 
2015-06-18 07:09:07.6231 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 07:14:07.6266 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 07:19:07.6360 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 07:24:07.6364 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 07:29:07.6429 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 07:34:07.6503 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 07:39:07.6537 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 07:44:07.6572 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 07:49:07.6696 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 07:54:07.6700 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 07:59:07.6755 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 08:04:07.6779 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 08:09:07.6893 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 08:42:45.5100 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 63MB. Private Memory Size: 50MB. GC Total Memory: 4MB 
2015-06-18 08:42:45.6400 [Warn] SyncTrayzor.Services.UpdateManagement.UpdateChecker: Fetching updates failed with an error System.Net.Http.HttpRequestException An error occurred while sending the request. Void ThrowForNonSuccess(System.Threading.Tasks.Task)    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Refit.RequestBuilderImplementation.<>c__DisplayClass28`1.<<buildCancellableTaskFuncForMethod>b__27>d__2a.MoveNext() in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient.<FetchUpdateAsync>d__0.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateNotificationClient.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateChecker.<FetchUpdateAsync>d__0.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateChecker.cs:line 82 System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'syncthing.antonymale.co.uk'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Refit.RequestBuilderImplementation.<>c__DisplayClass28`1.<<buildCancellableTaskFuncForMethod>b__27>d__2a.MoveNext() in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient.<FetchUpdateAsync>d__0.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateNotificationClient.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateChecker.<FetchUpdateAsync>d__0.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateChecker.cs:line 82
WebException The remote name could not be resolved: 'syncthing.antonymale.co.uk' System.Net.WebResponse EndGetResponse(System.IAsyncResult)
```

**Comment by canton7** [comment] 2015-06-18 11:46
Are you sure that log correlates with the crash? I don't see a gap in entries around the point that the crash occurred.

**Comment by canton7** [comment] 2015-06-18 11:47
Or, put another way, what time did the crash occur? It will be in the event log.

**Comment by Rewt0r** [comment] 2015-06-18 12:12
Apologies, ignore my previous post with errors from the log, they weren't the ones relating to the event log entry. The log stops at 9:20 this morning where as the exception occurred at 10:10?

**Comment by canton7** [comment] 2015-06-18 12:17
Huh, interesting. We should be logging every 5 minutes, at the least... What's in the log at 9:20?

**Comment by canton7** [comment] 2015-06-18 13:29
A long chat in `##csharp` later, and I think we may have to put some logging in. I *think* this might be being caused by the tray icon library, but I can't guarantee it...

**Comment by canton7** [comment] 2015-06-18 13:31
If it did an update check just before 9:20 that would be quite interesting indeed... Do you have that bit of the log?

**Comment by Rewt0r** [comment] 2015-06-18 13:36
I've just sent you the log files.

Here are the sequence of events to help explain some of the log file:

 - User reported files weren't syncing, I check the tray and move over the SyncTrayzor icon and it disappears (like the process had been terminated)
 - I re-open SyncTrayzor and it states Syncthing is still running, so I kill all and try to start Syncthing a couple of times
 - This doesn't work so I view the Syncthing log and notice that the unexpected kill from SyncTrayzor has corrupted the db

Come to think of it, I don't think the event log entry is anything to do with why SyncTrayzor had closed on this machine, as it's around an hour afterwards... Let me check his machine again for one earlier.

**Comment by Rewt0r** [comment] 2015-06-18 13:39
9:20 from event log:

```
Application: SyncTrayzor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Http.HttpRequestException
Stack:
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run()
   at SyncTrayzor.App.Main()
```

**Comment by canton7** [comment] 2015-06-18 13:45
That's really weird. At 8:42 SyncTrayzor was failing to talk to the update server. At 09:12:45 we log a normal memory usage entry, then at 09:19:47 we appear to have restarted. That's not a very big window we could have been dead in, and not enough time for the user to spot that files weren't syncing, for him to call you, and for you to restart it, surely?

At 09:20:08 we then successfully talk to the update server - so something's changed there.

At 09:20:12, Syncthing spots it has database corruption. Everything since then is SyncTrayzor recovering from Syncthing's crash. There are no entries in the log after 09:20, even though you should have restarted it?

**Comment by canton7** [comment] 2015-06-18 13:48
The exception that occurred at 09:20:18 will have shown SyncTrayzor's 'I crashed, please open a GitHub issue' dialog, and won't have caused it to quit silently.

**Comment by canton7** [comment] 2015-06-18 13:55
Is there absolutely nothing in the event log between 09:12:45 and 09:19:47?

**Comment by Rewt0r** [comment] 2015-06-18 14:00
At 8:42 it is possible that it didn't have connection as we've recently changed internet settings, I have a feeling the database corruption has been caused by a failing HDD which I made the user aware of last year.

The fact that it also ended on my work desktop (first error in the OP) may just be coincidence.

**Comment by Rewt0r** [comment] 2015-06-18 14:01
When SyncTrayzor is minimised I don't think that dialog opens up. There is nothing in the event log for those times.

**Comment by canton7** [comment] 2015-06-18 14:02
Can you think of any reason why SyncTrayzor may have restarted at 09:19:47?

Yeah, I think the first error is completely independent.

**Comment by canton7** [comment] 2015-06-18 14:05
What I see:

 - SyncTrayzor restarts
 - User starts Syncthing from the 'Syncthing -> Start' menu item (so the main window was open at that point)
 - Syncthing notices database corruption and crashes
 - SyncTrayzor doesn't handle this well, and also crashes

**Comment by canton7** [comment] 2015-06-18 14:09
I've just confirmed: SyncTrayzor (event version 1.0.18) does show the 'Oops! Something went badly wrong' window, even when it's just down in the tray, and when Syncthing crashes on startup

**Comment by Rewt0r** [comment] 2015-06-18 14:09
No idea why as I wasn't in the office then and the user wouldn't know how to open it?

**Comment by canton7** [comment] 2015-06-18 14:13
Although the error message in the event log does match what I see if I cause syncthing to crash on startup - so that's good at least.

Maybe the user rebooted their machine? Maybe they forced it to power down? Logged off? Something like that? That would explain Syncthing's database corruption at any rate.

Maybe the user saw and dismissed the 'Oops! Something went badly wrong' window before calling you over, not knowing what it was?

**Comment by canton7** [comment] 2015-06-18 14:16
Anyway, I've got a fix in place to not crash if Syncthing's database is corrupt. I think that's all I can do...

**Comment by Rewt0r** [comment] 2015-06-18 14:27
I don't think that was the case, as with my pcoess on my machine I didn't get the dialog either. I have a feeling that after so long Windows terminates the process with the Windows Error Reporting.

It may be possible that he restarted his machine, as it keeps freezing due to the HDD issue I've highlighted. There is a new machine on order in any case.

**Comment by canton7** [comment] 2015-06-18 14:34
On your machine you had an entirely different problem. If we get an error as a result of a filesystem notification, then that slips through a hole and won't trigger the  'Oops! Something went badly wrong' or log anything. However, the second crash is entirely different: it was not from a filesystem notification, and it *was* logged (which means the bit of code that logged it would also have shown the  'Oops! Something went badly wrong' window).

>  I have a feeling that after so long Windows terminates the process with the Windows Error Reporting.

That's certainly plausible...

**Comment by canton7** [comment] 2015-06-18 20:56
A fix for the first issue and better handling for the second are in 1.0.23

**Closed by canton7** 2015-06-18 20:56 UTC
