### ISSUE TITLE
SyncTrayzor won't run because I ran Syncthing 1.8 before I installed SyncTrazor

### ISSUE THREAD

**Issue by classicalguy** [canton7/SyncTrayzor#574] opened 2020-08-28 00:27 UTC
I installed Syncthing 1.8, which I ran from my download folder.  After setting things up, I learned about SyncTrayzor so it would have a tray icon.  Unfortunately, SyncTrayzor won't run because I need Syncthing 1.7 not 1.8, but I don't know how to uninstall 1.8 and start over.  Can anyone help?

**Comment by wzyboy** [comment] 2020-09-15 09:15
I encountered a similar issue as well. My Syncthing "raw" is 1.8 and the bundled Syncthing in SyncTrayzor is 1.2, so there is something like "configuration version too old" error in the startup log.

After downloading a newer version of Syncthing "raw" and manually place it in `C:\Users\<You>\AppData\Roaming\SyncTrayzor`, overwriting the bundled old version, SyncTrayzor can be started normally.

So just update the bundled Syncthing version and the issue will be gone.

**Comment by MoriarT3a** [comment] 2020-10-10 18:52
Thank you wzyboy.
That work's for me!

**Comment by canton7** [comment] 2020-10-11 17:26
Duplicate of #572

**Closed by canton7** 2020-10-11 17:26 UTC
