### ISSUE TITLE
Maxmizing from windows tray sometimes show just white window

### ISSUE THREAD

**Issue by Oriann** [canton7/SyncTrayzor#616] opened 2021-01-13 19:38 UTC
Synctrayzor 1.1.27
Syncthing 1.12.1
Windows 10 20H2 update

After update I am experiencing only white window after double-click on tray icon of SyncTrayzor. Closing window and repeating previous step will show syncthing interface as usual.

**Comment by tomparkinson** [comment] 2021-01-14 16:58
I am experiencing the same issue on 2 PCs, both with the same version info as mentioned above.

**Comment by nathanielcwm** [comment] 2021-01-15 11:18
I'm only experiencing it on one machine.

The PC that i'm only experiencing it on is high dpi so that may be a cause.

No issue:
20H2
1280x1024

2004/20H2 *sorry I forgot*
1920x1080

20H2
1366x768

Affected:
20H2
2560x1600

Issue doesn't go away when I reopen synctrayzor from tray. I have to force a refresh of the internal browser to fix the issue.

**Comment by nathanielcwm** [comment] 2021-01-15 11:24
hmm my issue is closer to #606 rather than this.

**Comment by tomwaldnz** [comment] 2021-01-17 19:06
I'm experiencing the same thing - white window, SyncThing working but can't see the UI. If I open the UI in the browser I can see it fine.

Unrelated, but I get a LOT of these types of messages in the logs - there's 101 in the log file since I started the machine about two hours ago.

[NZXXX] 06:25:46 INFO: Connected to myself (NZTXXXX) at [::]:22000-1.2.3.4:22000/quic-client/TLS1.3-TLS_AES_128_GCM_SHA256 - should not happen

**Comment by canton7** [comment] 2021-01-21 20:07
Could you please try getting the white screen, then open Chrome and point it at `http://localhost:2004`, and click the link to debug the embedded web interface in SyncTrayzor. See what's in the Elements and Console tabs, and if there are any clues as to why the interface is blank.

**Comment by tomwaldnz** [comment] 2021-01-22 01:15
http://localhost:2004/ shows me the content "Inspectable WebContents" with a link to (untitled tab)". The elements and console are completely empty. When I log into the web interface http://localhost:8384/ I can see it as normal. I've attached two screenshots below.

![image](https://user-images.githubusercontent.com/8381145/105432109-d9581400-5cbb-11eb-9d01-a68036abcfc0.png)


![st](https://user-images.githubusercontent.com/8381145/105432266-3358d980-5cbc-11eb-8bcf-8623547d3895.png)

**Comment by ahartmanns** [comment] 2021-01-28 14:01
I can confirm the occasional white screen issue on two systems (both on the current Windows 10 version). I think it happens most often when I've not opened SyncTrayzor for some time. I also tried the debugging with Chrome: I get the exact same behaviour as tomwaldnz reported in the post above.

**Comment by downtime0** [comment] 2021-02-01 23:58
I think i found the cause.
If you use the menu Syncthing --> Open in external browser --> (in browser UI) --> Actions -->Settings --> Default Folder Path; 
The default path indicates the tilde (~) symbol for root location when on Windows machine I know before the last upgrade I had a C:\ drive and a sub-path before. 
If you fix the "Default Folder Path" replacing the ~ back to your C:\ drive location and sub-path, the SyncTrazor app window will load correctly.

**Comment by nathanielcwm** [comment] 2021-02-02 14:04
Didn't help for me.

**Comment by tomwaldnz** [comment] 2021-02-02 18:11
> I think i found the cause.
> If you use the menu Syncthing --> Open in external browser --> (in browser UI) --> Actions -->Settings --> Default Folder Path;
> The default path indicates the tilde (~) symbol for root location when on Windows machine I know before the last upgrade I had a C:\ drive and a sub-path before.
> If you fix the "Default Folder Path" replacing the ~ back to your C:\ drive location and sub-path, the SyncTrazor app window will load correctly.

I found this didn't help me either, but thanks for sharing :)

**Comment by Oriann** [comment] 2021-02-02 18:13
> I think i found the cause.
> If you use the menu Syncthing --> Open in external browser --> (in browser UI) --> Actions -->Settings --> Default Folder Path;
> The default path indicates the tilde (~) symbol for root location when on Windows machine I know before the last upgrade I had a C:\ drive and a sub-path before.
> If you fix the "Default Folder Path" replacing the ~ back to your C:\ drive location and sub-path, the SyncTrazor app window will load correctly.

Nope this does not work..

**Comment by WarmChocolateCake** [comment] 2021-02-24 08:44
I'm brand new to SyncTrayzor and seeing this issue (with also ~50% CPU usage... I'll deal with that separately)
SyncTrayzor 1.1.27
Syncthing 1.13.1
Windows 10 Enterprise, ver 1909
If I "restore" (unmaximise) the SyncTrayzor window, close it, then re-open (so it's now opening un-maximised) then it appears to work, even if I maximised it again (and closed, and reopened...)
(Syncthing's default folder path is also ~ just for completeness)
Syncthing's GUI Theme is set to Dark in case that makes any difference at all...

**Comment by canton7** [comment] 2021-03-06 11:44
This is probably the same as #606, and a workaround is released in version 1.1.28. Please let me know if this doesn't fix your issue. Thanks!

**Closed by canton7** 2021-03-06 11:44 UTC

**Comment by janderk2** [comment] 2021-03-11 09:41
I have the same blank window issue on a Windows 2019 server for some time after reboots. Installed 1.1.28 yesterday and the server updated and rebooted last night. Same problem.

Opening Syncthing in Chrome on http://localhost:8384/ works just fine. If I manually shutdown Syncthing there, SyncTrazor will work again.

**Comment by tomwaldnz** [comment] 2021-03-11 17:18
@janderk2 try going into preferences and turning off hardware acceleration. That on the latest version has fixed the issue for me on two PCs.

**Comment by janderk2** [comment] 2021-03-11 20:48
OK will do.

**Comment by Oriann** [comment] 2021-03-22 11:29
After some time it happens again.

Here is vid: 

https://user-images.githubusercontent.com/11374526/111983230-32042b80-8b0a-11eb-817d-47a964cb1510.mp4

Version:
![image](https://user-images.githubusercontent.com/11374526/111983288-40eade00-8b0a-11eb-8b66-e545a69af7b2.png)
