### ISSUE TITLE
Crash on Windows Shutdown (Reference to Memory 0x00000059)

### ISSUE THREAD

**Issue by Vinpasso** [canton7/SyncTrayzor#121] opened 2015-07-03 23:23 UTC
Experienced a Crash this evening upon trying to shutdown the Workstation.

The crash effectively cancelled the shutdown, showing an error window that disappeared as Windows tried to log out, but failed.

Windows was left in a semi-logged of state, in which many Services/Applications had already been stopped but the System refused to shutdown/logoff.

The Windows log showed following Events:
```
Log Name:      System
Source:        Application Popup
Date:          04.07.2015 00:46:31
Event ID:      26
Task Category: None
Level:         Information
Keywords:      
User:          SYSTEM
Computer:      VTO-Desktop-W8
Description:
Application popup: SyncTrayzor.exe - Application Error : The instruction at 0xf65a662a referenced memory at 0x00000059. The memory could not be read.

Click on OK to terminate the program
Click on CANCEL to debug the program
```
10 seconds later in the log Windows gave up on trying to log off:
```
Log Name:      System
Source:        User32
Date:          04.07.2015 00:47:41
Event ID:      1073
Task Category: None
Level:         Warning
Keywords:      Classic
User:          %USER%
Computer:      %COMPUTER%
Description:
The attempt by user %COMPUTER%\%USER% to restart/shutdown computer %COMPUTER% failed
```

The syncthing.log shows that syncthing had an abnormal exit, likely causing synctrayzor to attempt to read this Memory Address. The syncthing log contained these lines after crash:
```
[63WOO] 00:36:06 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-wifialliance-org:service:WFAWLANConfig:1
[63WOO] 00:36:06 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-wifialliance-org:service:WFAWLANConfig:1
Syncthing process stopped with exit status 1073807364
Killing Syncthing process
```

This is the relevant section of the SyncTrayzor.log:
```
2015-07-04 00:45:09.6396 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 179MiB. Private Memory Size: 133MiB. GC Total Memory: 9MiB 
2015-07-04 00:45:11.2587 [Debug] SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher: Received 1 events 
2015-07-04 00:45:11.2587 [Debug] SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher: <GenericEvent ID=764 Type=Ping Time=04.07.2015 00:45:11> 
2015-07-04 00:46:02.3600 [Debug] SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher: Received 1 events 
2015-07-04 00:46:02.3600 [Debug] SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher: <GenericEvent ID=765 Type=Ping Time=04.07.2015 00:46:02> 
2015-07-04 00:46:31.2539 [Info] SyncTrayzor.Bootstrapper: Shutting down: Shutdown 
2015-07-04 00:46:31.2549 [Info] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClient: Requesting API shutdown 
2015-07-04 00:46:31.2847 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Syncthing process stopped with exit status 1073807364 
2015-07-04 00:46:31.2847 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Running -> Stopped 
2015-07-04 00:46:31.2847 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Running -> Stopped 
2015-07-04 00:46:31.2847 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Aborting API clients 
2015-07-04 00:46:33.2692 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Killing Syncthing process 
2015-07-04 00:46:33.2692 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Stopped -> Stopped 
```
I will try to replicate and debug this Crash tomorrow, hopefully I will be able to provide more information as to where Syncthing attempts to access memory at 0x00000059

**Comment by Vinpasso** [comment] 2015-07-03 23:30
As it may be relevant this is SyncTrayzor Version: 1.0.26.95 running on Windows 8.1
This is the Output of systeminfo:
```
Host Name:                 %COMPUTER%
OS Name:                   Microsoft Windows 8.1 Pro
OS Version:                6.3.9600 N/A Build 9600
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          %USER%
Registered Organization:
Product ID:                [REDACTED]
Original Install Date:     04.03.2014, 20:51:35
System Boot Time:          03.07.2015, 13:00:19
System Manufacturer:       To Be Filled By O.E.M.
System Model:              To Be Filled By O.E.M.
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 58 Stepping 9 GenuineInt
el ~3401 Mhz
BIOS Version:              American Megatrends Inc. P1.60, 12.09.2012
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             de;German (Germany)
Input Locale:              de;German (Germany)
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm,
 Vienna
Total Physical Memory:     8.144 MB
Available Physical Memory: 5.499 MB
Virtual Memory: Max Size:  12.240 MB
Virtual Memory: Available: 8.953 MB
Virtual Memory: In Use:    3.287 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\%COMPUTER%
Hotfix(s):                 159 Hotfix(s) Installed.
[List of 159 Hotfixes]
Network Card(s):           2 NIC(s) Installed.
                           [01]: Realtek PCIe GBE Family Controller
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.2.1
                                 IP address(es)
                                 [01]: 192.168.2.104
                                 [02]: fe80::6934:a37c:bb58:3cfd
                                 [03]: 2003:62:420a:a801:6dff:62d0:8f19:e5fc
                                 [04]: 2003:62:420a:a801:6934:a37c:bb58:3cfd
                           [02]: VirtualBox Host-Only Ethernet Adapter
                                 Connection Name: VirtualBox Host-Only Network
                                 Status:          Hardware not present
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```

**Comment by canton7** [comment] 2015-07-04 10:07
Interesting. I don't know why Syncthing exited in that way: I've asked the devs.

It's highly unlikely that the error `The instruction at 0xf65a662a referenced memory at 0x00000059. The memory could not be read` was caused by SyncTrayzor itself: it runs on .NET, which gives me an entirely managed environment which should prevent things like that from happening. It's far more likely that this was caused by the embedded browser (CEF) or its C# wrapper.

I'm using a version of the embedded browser which is a few versions out of date, as the newer versions contain a bug which would stop me from communicating with Syncthing over https. Unfortunately this means that raising a bug upstream for this would be pointless: it would get kicked back with the message "we don't support that version any more" (which is fair enough).

So. If you manage to replicate this, I think I'll have to wait for cefsharp/CefSharp#1104 to get resolved, then I can upgrade the embedded browser. We'll then see if it can be replicated *again*... If it can, *then* I'll be able to push a bug upstream.

Hope that all makes sense!

**Comment by Vinpasso** [comment] 2015-07-04 10:57
First of all, great work on SyncthingTrayzor and thank you for the fast reply.

As of yet, I have not been able to replicate this bug myself after various tests, and conclude that this is likely an extremely rare scenario causing cefsharp or cef to attempt to read invalid memory.

As of now I don't mind having this issue be closed or post-poned at will if desired, due to little/no urgency and need for a fix.

If this bug does turn up again I shall report back with the Debug Info.

Thanks for the help

**Comment by canton7** [comment] 2015-07-04 13:59
Thanks for trying to replicate it. Yeah I think the best course of action is to keep an eye open for its return, but otherwise leave it by now. I may well be that upgrading to the latest cefsharp, when I can, fixes the root cause anyway...

**Comment by canton7** [comment] 2015-07-06 12:59
Right, there's a build that uses CefSharp 41 here: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.26.99/artifacts

(Not much testing has been done, so it may be a bit unstable! But it should be even less likely to exhibit this issue than the current version...)

**Comment by Vinpasso** [comment] 2015-07-06 13:30
Ok, I will try the new build, however I deem it unlikely that the error will turn up again since it hasn't turned up after the first crash despite quite a bit of testing.

Anyhow, thanks for the effort and great work.

**Comment by canton7** [comment] 2015-07-06 14:09
Yeah I mention it mainly out of interest, or in case you had seen this re-appear.

**Comment by canton7** [comment] 2015-07-09 11:08
Closing as discussed

**Closed by canton7** 2015-07-09 11:08 UTC
