### ISSUE TITLE
SyncTrazor Unable to Start Syncthing

### ISSUE THREAD

**Issue by Carl249** [canton7/SyncTrayzor#490] opened 2018-12-11 05:11 UTC
SyncTrazyor displays "Syncthing Starting..." but then gets stuck and eventually a message window appears that says "Syncthing didn't start correctly" and "Unable to start Syncthing...Syncthing didn't connect after 00:10:00..."  During this 10 minute period the Syncthing console window at the bottom of SyncTrayzor repeats lines such as:
"TLS handshake error from 127.0.0.1:52983: tls: client offered an unsupported, maximum protocol version of 301" 
and in the SyncTrayzor log I see repeated lines such as:
"http:  TLS handshake error from 127.0.0.1:57186: tls: client offered an unsupported, maximum protocol version of 301".  However, despite these messages, Syncthing has actually been started by SyncTrayzor and the GUI is available via a web browser and Syncthing operates normally in syncing files.  I just can't use SyncTrayzor on this particular laptop anymore.

Everything had been working fine before for many months, and other laptops are still working fine.  This laptop is Windows Vista Home Premuim 32-bit and the others are Windows Vista Business 32-bit and Windows 7 Busines 32-bit. SyncTrayzor version is 1.1.22 and Syncthing is version 0.14.54  I haven't been able to figure out what is wrong on my own or by looking at forum posts yet.

**Comment by canton7** [comment] 2018-12-11 07:37
Are you *sure* you're running SyncTrayzor version 1.1.22? Someone on the forum had this exact problem, and it was caused by running an old version.

**Comment by Carl249** [comment] 2018-12-11 16:31
I double checked this morning by clicking on "Help" and it was 1.1.22.  When the problem started I was on a older version so I tried upgrading, downgrading to 1.1.14 and 1.1.16, and even uninstalling and re-installing, but unfortunately the problem persisted.

**Comment by Carl249** [comment] 2018-12-16 16:39
I still haven't figured out this handshake problem.  Is there additional information I can provide?

**Comment by canton7** [comment] 2018-12-18 12:36
Only that this was fixed in 1.1.20. I'm sorry for not believing you but it's the only possibility I can think of. Can you post a screenshot showing the About window and also the Syncthing console with those errors?

**Comment by Carl249** [comment] 2018-12-18 22:57
![capture](https://user-images.githubusercontent.com/45771411/50188074-2e532000-02d5-11e9-8fad-fa7b29d9cad8.JPG)

**Comment by canton7** [comment] 2018-12-18 23:08
You said the lines "TLS handshake error from 127.0.0.1:52983: tls: client offered an unsupported, maximum protocol version of 301" were appearing in the Synching console? They're not in your screenshot.

**Comment by Carl249** [comment] 2018-12-19 04:21
Here is a new screenshot.  Does this help?
![capture](https://user-images.githubusercontent.com/45771411/50198839-602eab80-0302-11e9-9301-f6520d4c63c1.JPG)

**Comment by canton7** [comment] 2018-12-19 07:56
Thanks. Hmm. What version of Windows are you running?

**Comment by Carl249** [comment] 2018-12-20 16:18
The affected laptop is running Windows Vista Home Premium 32-bit.  I have another laptop running Windows Vista Business 32-bit that is not having the problem.

**Comment by Carl249** [comment] 2018-12-31 18:48
Is there any other information I can provide that would help?

**Comment by ProactiveServices** [comment] 2019-02-18 22:22
> Ah, looks like Vista just doesn't support TLS 1.2, period. Vista is out of support, and hasn't received the updates necessary.
> Now, SyncTrayzor will try and connect to Syncthing using http, and Syncthing will then normally redirect it to https.
> Can you open up Syncthing's config.xml (in `C:\Users\<You>\AppData\Local\Syncthing`), and check whether it says `<gui enabled="true" tls="false"` or `<gui enabled="true" tls="true"`?

I've come across this on a Vista (!) machine as well; SyncTrayzor v1.1.22 x86 (.NET version: 4.5.2 (379893)) Syncthing 1.0.1 has tls="false" in its config.xml file. I've confirmed I can access http, without being redirected to https, via a web browser. Syncthing works and syncs with a connected device; it just seems to be SyncTrayzor's GUI that is attempting a TLS connection and not being able to.

With debug logging enabled:

> 2019-02-18 18:15:35.4794 #5360 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [VFCX4] 18:15:35 INFO: GUI and API listening on 127.0.0.1:8384 
> 2019-02-18 18:15:35.4814 #5360 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [VFCX4] 18:15:35 INFO: Access the GUI via the following URL: http://localhost:8384/ 
> 2019-02-18 18:15:36.4194 #5360 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: 2019/02/18 18:15:36 http: TLS handshake error from 127.0.0.1:51292: tls: client offered an unsupported, maximum protocol version of 301 
> 2019-02-18 18:15:36.4194 #5360 [Debug] SyncTrayzor.Syncthing.ApiClient.SyncthingApiClientFactory: Failed to connect on attempt 0

**Comment by liyafe1997** [comment] 2019-10-21 19:31
Vista didn't support TLS 1.2 at default. Follow this guide to enable:
https://johnhaller.com/useful-stuff/enable-tls-1.1-and-1.2-on-windows-vista
(Goto Windows update catalog website to install KB4056564(2018-05 Security Update for Windows Server 2008 for x86/x64-based Systems ), And import below reg file if you want to use TLS1.1/1.2 in Internet Explorer)

Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\AdvancedOptions\CRYPTO\TLS1.1]
"OSVersion"=-
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\AdvancedOptions\CRYPTO\TLS1.2]
"OSVersion"=-

**Closed** 2020-12-31 12:04 UTC
