### ISSUE TITLE
High memory usage (10GB+)

### ISSUE THREAD

**Issue by gijs007** [canton7/SyncTrayzor#141] opened 2015-09-14 11:23 UTC
I've now noticed twice that Sync Trayzor is using a high amount of memory.

This system has an Intel 750 PCIe NVMe SSD with a throughput of about 2 Gbps.
It's not doing this on any of my other systems which have normal SATA SSD's.

I also noticed that the directory that was being synced has been emptied completely on this system (despite most of the files being in synch).
![memory usage](https://cloud.githubusercontent.com/assets/11969278/9848660/7953c46c-5ae3-11e5-8c38-d2004baea1b9.png)

I can't upload the log file here, since it's bigger than 10MB. It's 25MB.
I tried uploading it to pastebin, but it's to large for them as well..

**Comment by canton7** [comment] 2015-09-14 11:45
That's ridiculously high! Can you find your log file? It will be in `%APPDATA%\SyncTrayzor\logs`.  Every ten minutes or so it will print some memory usage statistics. Mind pasting them here? 

I'm afraid I'm away this week so may be slow responding.

**Comment by gijs007** [comment] 2015-09-14 11:51
I've tried uploading the logs here, but they are to large. Even for site's as pastebin..

Instead I've put them in a zip file at: http://s000.tinyupload.com/?file_id=03752559906601610273

**Comment by gijs007** [comment] 2015-09-14 11:54
I'm actually having the issue on another machine as well, so it might not be related to the 
Do you want the log files of this machine too?

![memory usage lon](https://cloud.githubusercontent.com/assets/11969278/9849114/16c53e5c-5ae8-11e5-85c5-17dbdb3bef5c.png)

**Comment by canton7** [comment] 2015-09-14 13:14
I'm afraid I only have access to mobile thus week and can't extract any archives. If you search through the log file for the most. Recent occurrence of the word "memory"  and paste that line here (it should contain three numbers)  that will give me the information I'm after. Thanks

**Comment by gerbilOFdoom** [comment] 2015-09-16 03:26
@canton7 
On mobile, if android, you can use something like ES File Explorer or B1 Archiver to open up zip files

Here's a hastebin of the last couple thousand lines from the debug log: http://hastebin.com/pajezumeve.tex

If I'm reading it correctly then there are thousands of lines being written to the log in the space of a second. Perhaps this is the source of the memory usage?

**Comment by canton7** [comment] 2015-09-16 06:59
> If you search through the log file for the most recent occurrence of the word "memory" and paste that line here (it should contain three numbers) that will give me the information I'm after.

The log excerpt your pasted doesn't include this.

**Comment by gerbilOFdoom** [comment] 2015-09-17 03:13
@canton7 

There were no occurences of memory other than parts of the files he was downloading

**Comment by canton7** [comment] 2015-09-17 08:54
Ok fair enough. It looks like Syncthing's hitting a few problems: the log contains lots of "INFO: Puller: final: The data present in the reparse point buffer is invalid." and it's trying to pull files at a rate which gar exceeds anything I've ever seen. SyncTrayzor will be struggling to keep your with all of those events. 

I suggest you fix the problem with Syncthing first (Syncthing's log will be in `%LOCALAPPDATA%\syncthing`), and see if SyncTrayzor's performance improves. If you open an issue with Syncthing, including an excerpt from Syncthing's log I'm sure they'll be able to help.

**Comment by gijs007** [comment] 2015-09-17 14:46
Okay, I will report the problem with Synchting. Thanks for the reply's :+1:

**Comment by gijs007** [comment] 2015-09-18 21:38
Seems that disabling symlinks in the advanced options resolved the problem.

**Comment by canton7** [comment] 2015-09-20 15:48
Cool, thanks for letting me know! There's probably something I could do to sensibly rate-limit file transfer events (which should keep memory usage reasonable on cases like this), but since this scenario is very rare and there's no easy way to reproduce it, I'm inclined to leave that for now.

**Closed by canton7** 2015-09-20 15:48 UTC
