### ISSUE TITLE
Serious PC performance issues upon boot

### ISSUE THREAD

**Issue by jebeld17** [canton7/SyncTrayzor#410] opened 2017-09-23 14:47 UTC
My PC experiences serious performance issues upon boot if SyncTrayzor is set to open in the background upon login. Synctrayzor eventually hangs up performance so much after logging in that the app fails to respond, turning the tray icon grey indicating SyncThing has stopped. 
Windows will eventually give me an error message asking me to force-quit SyncTrayzor because it refuses to respond, but even then just that "force close/quit" prompt can take as long as three minutes to load.

See the included System Reliability Monitor XML export file and MSINFO32 export under the Attachments.

**Attachments:**
[msinfo32_export.txt](https://github.com/canton7/SyncTrayzor/files/1326604/msinfo32_export.txt)
[ReliabilityHistory-09.23.2017.xml.zip](https://github.com/canton7/SyncTrayzor/files/1326606/ReliabilityHistory-09.23.2017.xml.zip)

**Comment by Smallous** [comment] 2017-09-28 20:55
I am new to SyncTrayzor, so bare with me. "open in the background upon login" is the background part something you modified in a config file somewhere as I only have 'Automatically start on logon' as an option?

Have you ruled out if this is a Windows 10 Insider Preview version bug?

**Comment by canton7** [comment] 2017-10-02 11:45
Can you post your log, maybe there's a clue in it. Go to File -> Settings -> Logging + STTRACE -> Show SyncTrayzor log file. You might have to increase the log level to Debug and reproduce the issue to get interesting output.

**Comment by jebeld17** [comment] 2017-10-04 10:06
[syncthing.log](https://github.com/canton7/SyncTrayzor/files/1355383/syncthing.log)
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/1355384/SyncTrayzor.log)
[syncthing.439.log](https://github.com/canton7/SyncTrayzor/files/1355385/syncthing.439.log)
[syncthing.440.log](https://github.com/canton7/SyncTrayzor/files/1355386/syncthing.440.log)
[syncthing.441.log](https://github.com/canton7/SyncTrayzor/files/1355390/syncthing.441.log)
[SyncTrayzor.453.log](https://github.com/canton7/SyncTrayzor/files/1355387/SyncTrayzor.453.log)
[SyncTrayzor.454.log](https://github.com/canton7/SyncTrayzor/files/1355388/SyncTrayzor.454.log)
[SyncTrayzor.455.log](https://github.com/canton7/SyncTrayzor/files/1355389/SyncTrayzor.455.log)

**Comment by canton7** [comment] 2017-10-04 11:20
There are a couple of crashes in there, but nothing which indicates a slowdown.

**Comment by canton7** [comment] 2017-10-05 13:41
Grr, I wrote a message here yesterday and it seems to have vanished.

It looks like disk corruption. Some of the log files have a bunch of null bytes in them, and the error message indicates that the log file does too.

I've improved the error handling for this case, but it looks like the root cause is probably disk failure.

**Comment by jebeld17** [comment] 2017-10-08 07:52
Hey, I just read your message.

I actually beg to differ, but I did back up my information just in case.

The reason behind why I'm begging to differ is because this is happening on not only one PC, but two completely different PCs running completely different internal components, on the same version of Windows, 10 v1709 (RTM).

**Comment by jebeld17** [comment] 2017-10-08 07:53
And PS:
Your comment didn't disappear. You responded to a similar (but not identical) error I've reported at #412.

😊

**Comment by canton7** [comment] 2017-11-27 13:07
Closing as this is the same disk corruption issue.

**Closed by canton7** 2017-11-27 13:07 UTC
