### ISSUE TITLE
Synctrayzor crash after wakeup from sleep, persists when trying to re launch.

### ISSUE THREAD

**Issue by Nihim** [canton7/SyncTrayzor#93] opened 2015-05-25 10:14 UTC
>>System.Exception: Unable to find Syncthing at path F:\Syncthing\SyncTrayzorPortable-x64\syncthing.exe
at SyncTrayzor.SyncThing.SyncThingProcessRunner.Start() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingProcessRunner.cs:line 94
at SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__14.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ShellViewModel.<Start>d__10.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

The syncthing.exe really isn't there. It exists one dir up but that might be cause I unpacked synctrayzor inside the syncthing dir (so that might be the old syncthing.exe). I am using the "custom home" for the syncthing files.
What looks weird for me it's that it's quoting the location of what looks like your files?

Restarting synctrayzor throws the same error.
There is no syncthing process still running.

LOG:

>>2015-05-25 12:28:13.0115 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Stopped -> Starting 
2015-05-25 12:28:13.0366 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Stopped -> Starting 
2015-05-25 12:28:13.0366 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Starting syncthing: F:\Syncthing\SyncTrayzorPortable-x64\syncthing.exe 
2015-05-25 12:28:13.3366 [Error] SyncTrayzor.Bootstrapper: An unhandled exception occurred System.Exception Unable to find Syncthing at path F:\Syncthing\SyncTrayzorPortable-x64\syncthing.exe Void Start()    at SyncTrayzor.SyncThing.SyncThingProcessRunner.Start() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingProcessRunner.cs:line 94
   at SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__14.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ShellViewModel.<Start>d__10.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler) System.Exception: Unable to find Syncthing at path F:\Syncthing\SyncTrayzorPortable-x64\syncthing.exe
   at SyncTrayzor.SyncThing.SyncThingProcessRunner.Start() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingProcessRunner.cs:line 94
   at SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__14.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ShellViewModel.<Start>d__10.MoveNext() in c:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
2015-05-25 12:28:13.4166 [Debug] SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient: Fetched updates response: <UpdateNotificationResponse data= error=> 
2015-05-25 12:28:13.4166 [Info] SyncTrayzor.Services.UpdateManagement.UpdateChecker: No updates available 

Cheers

**Comment by canton7** [comment] 2015-05-25 10:28
So SyncTrayzor.exe exists in `F:\Syncthing\SyncTrayzorPortable-x64`, but syncthing.exe doesn't? If so, that means you must have deleted syncthing.exe from that location, since it's included there in the portable zip. 

SyncTrayzor won't work if you delete files included in its zip.

It's normal for stack traces to include the locations of files as they were when the project was built.

**Comment by Nihim** [comment] 2015-05-25 10:36
I know stuff like that is usually human error but I am pretty sure I didn't delete it. It was running fine past days without me accessing said dir and after waking up the pc today the problem appeared.

I used one of the backups so it's running but it's weird. Checked AV incase it somehow decided it was the enemy of all mankind and quarantined it but nope.

Guess close the ticket until (if) it happens again?

**Comment by canton7** [comment] 2015-05-25 10:38
Maybe a syncthing upgrade broke it? If the restored-from-backup syncthing.exe wants to auto-upgrade, let it, and see if that reproduces the issue.

**Comment by Nihim** [comment] 2015-05-25 10:46
that's what ones of the things I checked. The backup is the latest version.

**Comment by canton7** [comment] 2015-05-25 10:50
In that case I'd be inclined to agree with you and suspect some over-ebthusiastic anti-malware program. 

Let's see if it happens again. Leave the issue open: I'll put a better error message in for this scenario.

**Comment by Nihim** [comment] 2015-05-25 10:56
Alright, will do thanks!

ps: Unless my AV settings changed it doesn't straight delete files it quarantines them and if I am not mistaken it also notifies / prompts me.

**Comment by canton7** [comment] 2015-05-25 11:08
Weird. SyncTrayzor will never delete that file on its own, and it does require it, so *something* external must have happened.

**Comment by canton7** [comment] 2015-05-25 11:13
Just in case: AV quarantining typically does delete the file from disk. Also check you don't have more than one AV running

**Comment by Nihim** [comment] 2015-05-25 11:53
Yea but it would list it in the quarantine list / logs. And ofcourse not running 2 AVs :P

**Comment by Rewt0r** [comment] 2015-05-27 20:21
If you use 360 Total Security and the 32-bit version of Syncthing it normally detects it as a virus, as it does with any 32-bit Go application I've tested... I have reported it to them and seems to be fixed in the latest version so if you use that try updating.

**Comment by Nihim** [comment] 2015-05-27 21:19
Thx but I guess what I said above would still happen: there would (should) be some kinda of entry on the logs.
Using Avast btw.

**Comment by canton7** [comment] 2015-06-02 11:23
I'm assuming that this hasn't re-appeared?

I've got a better error message in there now, so I'll close this. Feel free to re-open if the issue re-appears.

**Closed by canton7** 2015-06-02 11:23 UTC
