### ISSUE TITLE
console scrolling

### ISSUE THREAD

**Issue by odgeza** [canton7/SyncTrayzor#126] opened 2015-07-27 18:53 UTC
Is it just me that has the issue, that when there is a lot of data in the console, i have to keep scrolling down instead of a "scroll with new data" or "stay were its at" method?

**Comment by canton7** [comment] 2015-07-27 19:34
Never seen that myself It might just be you :wink:

**Comment by odgeza** [comment] 2015-07-27 19:43
Its very reproducable for me. Seems like when hardware acceleration is disabled (on the VMs that I connect to with RDP), it doesnt do it? 

You know the code, do think thats possible? Basically the scroll for new line does exactly the opposite on them, it goes to the first line, instead of the last line. If I disable hardware acceleration, it correctly goes to the last line.

**Comment by canton7** [comment] 2015-07-27 19:46
I was kidding - I'll investigate. The hardware acceleration and the console scrolling are completely independent things - there's no way that one is affecting the other.

**Comment by odgeza** [comment] 2015-07-28 07:09
IT only happens after there is a lot of log data. (And after the browser dissappears - though might not be related). Hardware acceleration has no impact.

When I return to the server,it was scrollong correctly (but with no browser visible). If i click anywhere or scroll up and down, it then breaks it.

**Comment by canton7** [comment] 2015-07-28 08:09
When you say it "breaks it" - is data still being output to the console window - i.e. is the scroll bar getting smaller, etc? Or is data still being added to the console window, but it isn't scrolling down to the bottom (it's an important distinction)?

**Comment by odgeza** [comment] 2015-07-28 11:13
Sorry, I should have been a bit clearer. By break it, I mean, data is being added, but it reverts to "let me take you to the top of the window each time a line is added"

**Comment by canton7** [comment] 2015-07-28 11:31
Which is really quite odd, because we're literally calling `ScrollToEnd()` on the TextBox whenever new data is added (see [here](https://github.com/canton7/SyncTrayzor/blob/master/src/SyncTrayzor/Xaml/ScrollToEndBehaviour.cs#L30)). Let me do some googling...

**Comment by odgeza** [comment] 2015-07-28 12:20
i can give you a video of the behaviour if you want, just not sure where to put it

**Comment by canton7** [comment] 2015-07-28 12:30
That would be helpful if you don't mind! Dropbox?

**Comment by odgeza** [comment] 2015-07-28 12:44
shared with your email from google drive

**Comment by canton7** [comment] 2015-07-28 13:22
OK thanks, that helps. One thing I notice is that you're getting loads of log messages, which might be a factor. Is it an issue when you turn down the logging frequency (i.e. don't set STTRACE)?

**Comment by odgeza** [comment] 2015-07-28 14:11
yeah, but i need it for when my issues crop up. perhaps you can see if you get the issue with a load of log data.

**Comment by canton7** [comment] 2015-07-28 14:44
I'm trying to chase down the issue. I'm not suggesting removing STTRACE as your "fix" - I'm trying to determine whether having lots and lots of messages is a factory in causing the issue to occur.

**Comment by canton7** [comment] 2015-07-28 14:57
I've stress-tested that console window quite extensively in the past, and again just now. I can't reproduce this issue, which means that it's specific to you and your setup, and also means that I can only debug it with your cooperation :smile: 

Another interesting thing about your video is that messages should be written to the console in chunks every half-second, whereas your messages are appearing more frequently than this. When the console window isn't "broken", do they still arrive in a constant stream, or do they correctly arrive in half-second chunks?

**Comment by canton7** [comment] 2015-07-28 15:14
Also, what version of SyncTrayzor? Just to check...

**Comment by canton7** [comment] 2015-07-29 06:56
So, is it still an issue when you turn down the logging frequency?

**Comment by odgeza** [comment] 2015-07-29 07:14
Have set one of my hosts to no debug output.

**Comment by odgeza** [comment] 2015-08-03 07:45
"eventually" yes, it just takes longer to get to that point

**Comment by canton7** [comment] 2015-08-03 08:24
Ah, I hadn't appreciated that it only happens after a certain number of messages. That's very useful info.

Could you send me the contents of the console window at the point that it starts breaking? I'm interested in whether the number of lines, or maybe the number of characters, is triggering this.

Thanks!

**Comment by odgeza** [comment] 2015-08-03 09:11
The thing is, I'm not watching it, I come back to it, and its broken, so will this actually be useful or not? (I may have missed it for an hour already)

**Comment by canton7** [comment] 2015-08-03 10:41
(Oops, I added wontfix to the wrong issue)

It will probably be better than nothing: it will give a ballpark, at least.

**Comment by canton7** [comment] 2015-10-24 13:46
Hi, any more input on this?

**Comment by canton7** [comment] 2015-12-03 19:03
Closing due to inactivity

**Closed by canton7** 2015-12-03 19:03 UTC
Labels: waiting-for-OP
