### ISSUE TITLE
Syncthing can not be started

### ISSUE THREAD

**Issue by theincogtion** [canton7/SyncTrayzor#226] opened 2016-02-03 09:07 UTC
I stopped syncthing via synctrayzor. Afterwards, the button "start syncthing" is grey and I can not start syncthing again.
OS: Win 8.1 x64
STrayzor: 1.1.6

![image](https://cloud.githubusercontent.com/assets/10852327/12777524/e4f02f78-ca5d-11e5-9bfe-d7bba637598f.png)

**Comment by canton7** [comment] 2016-02-03 09:43
Looks like it thinks Syncthing is in the middle of shutting down, but hasn't actually stopped yet...

Please attach your log file, or at least the last 50 or so lines of it. You'll find it in `C:\Users\<You>\AppData\Roaming\SyncTrayzor\logs\SyncTrayzor.log` for the installed version, and `logs\SyncTrayzor.log` for the portable version.

**Comment by canton7** [comment] 2016-02-03 09:52
Hmm, that log looks absolutely fine.

At 2016-02-03 09:54:00, were the options in the 'Syncthing' menu definitely greyed out, as in your screenshot?

**Comment by theincogtion** [comment] 2016-02-03 09:53
I can not check it anymore :)
At the moment it is working fine again. I will keep an eye on that,

**Comment by canton7** [comment] 2016-02-03 09:55
I need the log entries which correspond exactly with when you saw the problem.

The log is large enough that it should still have entries from when you took the screenshot. If you can remember roughly when you took the screenshot, you should be able to find the corresponding lines in the log (or send me the whole thing and I'll try and find what I'm after).

**Comment by theincogtion** [comment] 2016-02-03 10:02
Screenshot ist from 10:06 .... So I gave you the wrong Log sorry.
I resend you a mail.

**Comment by canton7** [comment] 2016-02-03 10:08
Just so that I can be sure I'm looking at the right bit...

Did you open the menu, see that 'Start' was not available, click 'Kill all Syncthing processes', take the screenshot, then restart SyncTrayzor?

Could you please send me the 100 or so lines before the lines you sent me? I can see the point at which things had gone wrong, but not the events leading up to the problem.

**Comment by theincogtion** [comment] 2016-02-03 10:11
Yes correct after and before I clicked on "Kill all" it was grey.

**Comment by canton7** [comment] 2016-02-03 10:34
Cool, thanks. Let me go through that latest log...

**Comment by canton7** [comment] 2016-02-03 10:37
That's really weird: it shut down normally: everything happened as it should. I'll investigate what could have caused the UI to not update properly.

**Comment by canton7** [comment] 2017-03-19 21:37
I've only had this reported in one case, and I'm pretty sure it can only be a weird Windows issue where it doesn't update the state of UI elements, or something funky. Closing as I have no way to reproduce.

**Closed by canton7** 2017-03-19 21:37 UTC

**Comment by sylent3524** [comment] 2019-04-06 05:10
I am seeing what seems to be the same issue. Installed fine, worked fine; suddenly stopped.
