### ISSUE TITLE
Empty browser windows  get opened during update

### ISSUE THREAD

**Issue by May2002** [canton7/SyncTrayzor#49] opened 2015-04-16 11:52 UTC
So here is what happened:

SyncTrayzor 1.0.12 asked for being updated when the computer was launched,
no other program was running then.
I accepted and it opened two Firefox windows with 
 - the GitHub page and no other opened tab on one, and 
 - no tab at all on the other.
As I closed the browser the last time I had 2 windows with about 140 tabs per window.
I have had access to the last session restore recent function in the tool menu so nothing was lost.

Maybe my session was still somewhere else, but the two windows led me to think that it was gone.
I used to have the same kind of problem with the flash player updates, each time having to restore sessionstore.js (until I removed it). But as I said maybe the issue is on my side. And I don't know how the session manager works now.

Regards...

**Comment by canton7** [comment] 2015-04-16 11:57
Thanks for reporting this.

OK, so the issue is that:

1. An empty window was opened.
2. Asking Firefox to open a web page caused it to forget about your previous session.

Is that fair?

**Comment by canton7** [comment] 2015-04-16 12:11
I'm not sure why two browser windows were opened - I think that's some custom configuration you've got in Firefox. SyncTrayzor asks the OS to open a single URL, and on my system that results in a single browser window.

If you go to menu (the 3 horizontal stripes in the top right) -> History -> Restore Previous Session, Firefox should restore your previous session. Again, I don't think there's a lot I can do here: I'm just asking the OS to open a URL using a suitable browser.

My understanding is that Session Restore is more like a backup than anything else: it's like deleting your files assuming you can restore them from the Recycle Bin, then being upset when the Recycle Bin is emptied. To improve on this, you can either install an extension such as [Session Manager](https://addons.mozilla.org/en-us/firefox/addon/session-manager/) (which does properly and permanently store your sessions), or save all tabs as bookmarks in a folder before exiting (much as you'd save a Word document before exiting).

Starting with the 1.0.13 installed version (not portable), upgrades will (well, should!) be done semi-automatically, without a browser window needing to be opened, but there are plenty of other places where you can get SyncTrayzor to open a browser window.

**Comment by canton7** [comment] 2015-04-16 12:44
As in experiment, could you open up the Run dialog (windows + R, or it's in the start menu somewhere), enter 'http://www.google.co.uk', and hit 'OK'? I want to see whether that opens 1 or 2 windows. Thanks!

**Comment by May2002** [comment] 2015-04-16 14:01
Thanks for the tips regarding Firefox.
I can add that on a computer with the browser already opened it just opened a new tab.
I'll do what you say as soon as I get to see the right computer.

**Comment by canton7** [comment] 2015-04-16 15:54
OK great, thanks!

**Comment by May2002** [comment] 2015-04-16 18:45
Hi again, it does what I would have expected:
it opens the two windows with all their tabs and adds the google tab in one of them.

**Comment by canton7** [comment] 2015-04-16 18:56
OK, so I don't think there's anything I can do here: something in your system setup is causing two windows to be opened even though we only ask for one. Are you happy for me to close this?

**Comment by May2002** [comment] 2015-04-16 19:13
I dont get what you mean.
On this computer I use Firefox with two windows at the same time because I have so many tabs (I hope the situation won't last too long, though). So I'm happy with what I got following your instructions, that's what usually happens with links comming from other programs. It is a bad surprise when things don't work this way, but I can get around.

Anyway this is not important since you told that soon the upgrades won't open a browser window/tab!

So OK, you can close this, and sorry for the inconvenience.

**Comment by canton7** [comment] 2015-04-16 19:29
Aha, I mis-understood: I thought that two windows were unexpected. No worries - thanks for helping to investigate this. Maybe I should make it clearer in the UI when clicking something will open a browser window...

**Closed by canton7** 2015-04-16 19:29 UTC

**Comment by canton7** [comment] 2015-04-17 14:14
Turns out I messed up the auto-upgrader in v1.0.13, so v1.0.14 will have to be installed manually. v1.0.15, however, should install in a much nicer way :smiley:
