### ISSUE TITLE
v1.0.14: crash after start

### ISSUE THREAD

**Issue by chucic** [canton7/SyncTrayzor#55] opened 2015-04-18 16:54 UTC
After installing new version, SyncTrayzor starts, syncthing starts, last shown log entry on "Starting web GUI" and then it show "Ups" warning with this:

```
Refit.ApiException: Response status code does not indicate success: 500 (Internal Server Error).
   v SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__23.MoveNext() v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:řádek 305
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__14.MoveNext() v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:řádek 175
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:řádek 20
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v SyncTrayzor.Pages.ShellViewModel.<Start>d__6.MoveNext() v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:řádek 72
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   v System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   v MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment] 2015-04-18 17:18
So Syncthing chucked a 500 at us - indicating an internal error of some sort.

Can you grab the end of `SyncTrayzor.log` - for installed versions it'll be in `C:\Users\<You>\SyncTrayzor\logs\SyncTrayzor.log`, for portable version it'll be in `data\logs\SyncTrayzor.log`? That will tell us what Syncthing logged, which may give a clue.

**Comment by chucic** [comment] 2015-04-18 18:04
Took some time to clean IDs.

New version starts 18:37, then one or more starts to make its persistent, then reinstall to v1.0.13, then again to new one and after some time to old one, so its little confusing.

https://gist.githubusercontent.com/chucic/e74c51097bdd913cf6e3/raw/gistfile1.txt

**Comment by prestonwii** [comment] 2015-04-18 19:45
I'm having this same problem after updating. This is the first real problem I've had with SyncTrayzor, it is a great program.

**Comment by canton7** [comment] 2015-04-18 19:46
@prestonwii Are you using Syncthing 0.11 as well?

**Comment by locksmithone** [comment] 2015-04-18 19:47
I have the same issue; may I add, however, that the path indicated in chucic's post is the same that appears in mine ("h:\Users\Antony\Documents\projects\SyncTrayzor\..."). It is evidently not chucic's, or mine. Maybe that has something to do with it?

0.11 x64 non-portable here.

**Comment by canton7** [comment] 2015-04-18 19:49
Looks like 0.11-rc1 changed something in the API, relative to 0.11-beta6. Let me find out what...

The file paths shown in the stack trace are relative to where SyncTrayzor was compiled - that's expected.

**Comment by prestonwii** [comment] 2015-04-18 19:49
Yes, I'm using the 0.11.0-rc0 version of syncthing. I can start the version that is being run by SyncTrayzor outside of SyncTrayzor without issues.

**Comment by locksmithone** [comment] 2015-04-18 19:55
It seems that frequently syncthing updates its things, and breaks everybody else's overlays. :)

**Comment by canton7** [comment] 2015-04-18 19:59
Hrm, it's failing to get the ignores list for one of your folders: we retrieve 4 of them find, then Syncthing throws an error at us. Unfortunately I'm not logging the body of the error it returns, so... I can't reproduce it here either, so it's something quite specific.

Tell you what: could you open up `SyncTrayzor.exe.config` (which will be in the same folder as `SyncTrayzor.exe`, and change the `<nlog>` section at the bottom to:

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <targets>
        <target name="logfile" type="File"
                fileName="${gdc:item=LogFilePath}\SyncTrayzor.log"
                createDirs="True"
                archiveFileName="${gdc:item=LogFilePath}\logs archive\SyncTrayzor.{#}.log"
                archiveAboveSize="52428800"
                archiveEvery="Day"
                archiveNumbering="Sequence"
                maxArchiveFiles="1"
                autoFlush="True"
                layout="${longdate} [${level}] ${logger}: ${message} ${exception:format=type,message,method,stacktrace,tostring:maxInnerExceptionLevel=10:innerFormat=shortType,message,method}"/>
        <target name="debugger" type="Debugger"
                layout="${time} [${level}] ${logger:shortName=true} ${message}"/>
        <target name="syncthinglogfile" type="file"
                fileName="${gdc:item=LogFilePath}\syncthing.log"
                createDirs="True"
                archiveFileName="${gdc:item=LogFilePath}\logs archive\syncthing.{#}.log"
                archiveAboveSize="52428800"
                archiveEvery="Day"
                archiveNumbering="Sequence"
                maxArchiveFiles="1"
                layout="${message}"/>
      </targets>
      <rules>
        <logger name="SyncTrayzor.SyncThing.SyncThingProcessRunner" minlevel="Debug" writeTo="syncthinglogfile"/>
        <logger name="*" minlevel="Trace" writeTo="logfile"/>
        <logger name="*" minlevel="Trace" writeTo="debugger"/>
      </rules>
    </nlog>
```

Then reproduce the problem and grab the log file again. That will enable more logging, which should give us the information we need.

To get the code formatting, use backticks (see https://guides.github.com/features/mastering-markdown/, under 'Code').

**Comment by canton7** [comment] 2015-04-18 20:01
> It seems that frequently syncthing updates its things, and breaks everybody else's overlays. :)

That's the problem with using the unreleased betas :smile:

**Comment by canton7** [comment] 2015-04-18 20:47
As a workaround, you can download Syncthing 0.11-beta6, and place it in `C:\Users\<You>\AppData\Roaming\SyncTrayzor` (installed), or in the main folder (portable). You'll also need to go to Settings -> Syncthing -> Advanced, and check 'Stop Syncthing auto-upgrading'.

**Comment by chucic** [comment] 2015-04-18 21:00
Done. Errors from app:

```
Refit.ApiException: Response status code does not indicate success: 500 (Internal Server Error).
   v SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__23.MoveNext() v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:řádek 305
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__14.MoveNext() v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:řádek 175
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:řádek 20
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v SyncTrayzor.Pages.ShellViewModel.<Start>d__6.MoveNext() v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:řádek 72
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   v System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   v MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

Log file:
https://gist.github.com/chucic/ba71909686cffaa6ddf6#file-gistfile1-txt

Also, I forgot to mention that with v1.0.13 I'm using syncthing v0.11.0-rc0 without problems.

    And this is cool...

**Comment by canton7** [comment] 2015-04-18 21:21
Ah, so Syncthing's claiming that some of your folders don't exist, despite just having told us that they do...

I suspect there's something timing-related here - maybe v1.0.13 leaves it slightly longer before querying for folders?

**Comment by canton7** [comment] 2015-04-18 23:12
Thanks! Issue opened, let's see what the response.

I suspect Syncthing hasn't loaded the folders in question - but I don't know that there's much I can do currently, other than waiting for "a bit". There is a `StartupComplete` event on the events interface, but I'm not guaranteed to catch it, especially if I reconnect to Syncthing, so I can't rely on it...

**Comment by chucic** [comment] 2015-04-18 23:34
No problem and thank YOU for this great wrapper. Whole universe of syncthing is just getting better and better every day. Awesome!

**Comment by canton7** [comment] 2015-04-19 12:12
I've put a workaround in place. Could you try this intermediate build and let me know whether it works for you, please? (I can't test it myself as I can't replicate the issue). If it does, I'll turn it into a release. Thanks!

https://s3-eu-west-1.amazonaws.com/canton7/SyncTrayzorSetup-x64-issue-55-15ec376.exe

**Comment by chucic** [comment] 2015-04-19 13:58
Unfortunately with this build I wont even get main window, instead shows immediately this error ¨:

```
System.NullReferenceException: Odkaz na objekt není nastaven na instanci objektu.
   v SyncTrayzor.Services.Config.ConfigurationProvider.MigrateV1ToV2(XDocument configuration) v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:řádek 172
   v SyncTrayzor.Services.Config.ConfigurationProvider.MigrationConfiguration(XDocument configuration) v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:řádek 163
   v SyncTrayzor.Services.Config.ConfigurationProvider.LoadFromDisk(Configuration defaultConfiguration) v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:řádek 121
   v SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:řádek 100
   v SyncTrayzor.Bootstrapper.Configure() v h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Bootstrapper.cs:řádek 79
   v Stylet.BootstrapperBase.Start(String[] args)
   v System.Windows.Application.<.ctor>b__1(Object unused)
   v System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   v MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

First line says "Shortcut/reference to object isn't set to instance of object."

**Comment by canton7** [comment] 2015-04-19 15:43
Oops, sorry about that! Try this one:

https://s3-eu-west-1.amazonaws.com/canton7/SyncTrayzorSetup-x64-issue-55-57b4192.exe

**Comment by chucic** [comment] 2015-04-19 16:07
Now it works. With both syncthing rc0 and rc1. And it even remembers windows size and position, GREAT!

Only key shortcuts for zoom do not work, but mouse wheel does.

**Comment by canton7** [comment] 2015-04-19 16:17
Interesting. Click within the embedded browser, then try again? Thanks for testing this!

**Comment by chucic** [comment] 2015-04-19 16:22
Tried, no change. But even before I had focus in browser, otherwise I couldn't do it with mouse wheel.

You're welcome. But thanks goes to you for working on this piece of software.

**Comment by canton7** [comment] 2015-04-19 16:28
Hmm ok thanks, I'll look at those.

**Comment by canton7** [comment] 2015-04-19 20:29
Righty, currently I've only got shortcuts for the + and - between the numbers and backspace on the keyboard - not for those on the numpad: I'll add those in. Does ctrl+0 work to reset the zoom?

**Comment by chucic** [comment] 2015-04-19 20:44
~randomly hitting keys~
EN keyboard: 0 and - works normally, + only with ctrl+shift++.
CS keyboard: 0 works normally, - I have next to the right shift and + only with ctrl+shift+"where - is on EN keyboard, on the right to the 0", weird.

So it works, thanks.
...although numpad would be much better.

**Comment by canton7** [comment] 2015-04-19 20:47
I'll add bindings for ctrl+=, and the numpad

**Comment by Belphemur** [comment] 2015-04-20 06:19
Hello @canton7 
I installed the last build on this issue (since I got the same problem), but it seems SyncTrayzor want to access C:\Program Files\SyncTrayzor\data\config-backup where the folder data doesn't exist
This is the stacktrace : https://gist.github.com/Belphemur/1b47e992f3431d56c1b7

**Comment by canton7** [comment] 2015-04-20 07:18
Fixed, thanks! I'm hoping to get 1.0.15 out today

**Comment by Belphemur** [comment] 2015-04-20 07:22
Ho and I tried to create the folders manually, since it's a system folder and SyncTrazor is launch as user, it can't write in the folder.

**Comment by canton7** [comment] 2015-04-20 07:25
Yeah - it should be trying to write to `C:\Users\<You>\AppData\Roaming\SyncTrayzor\config-backups`, but due to a small mess-up in the config, it's trying to use the portable version's paths (which are relative to where the .exe is).

If you want a "real" short-term fix, open up `SyncTrayzor.exe.config` (next to `SyncTrayor.exe`), find the `<PathConfiguration>` bit, and add the line `<ConfigurationFileBackupPath>%APPDATA%\SyncTrayzor\config-backups</ConfigurationFileBackupPath>`

**Comment by canton7** [comment] 2015-04-20 09:10
This should all be fixed in v1.0.15, which is now out. Thanks!

**Closed by canton7** 2015-04-20 09:10 UTC

**Comment by chucic** [comment] 2015-04-20 09:30
Everything works fine for me. Thanks a lot.

Now I'm only missing remembering of position of "command line log" and I have to restart to check for 2 more things.

**Comment by canton7** [comment] 2015-04-20 09:31
Yeah - I'll raise an issue for that position. It should be pretty easy to get in, but I wanted to get v1.0.15 out ASAP to fix the pending issues.

**Comment by chucic** [comment] 2015-04-20 10:16
I was planning to raise it too after checking some other things, so thanks. Now I discovered one more thing (#57) and I have one I know about some time, but I don't know terminology for that, so I didn't know how to explain. Now I tried in #58.
