### ISSUE TITLE
Crash opening "Conflict Resolver"

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#199] opened 2016-01-12 09:31 UTC
Steps done:
1 - conflicts present, open resolver via yellow bar, resolve all.
2 - close conflict resolver
3 - let it be for a while
4 - open Conflict Resolver via menu (there are not supposed to be any conflicts atm)
5 - instant crash:
```
Version: 1.1.1.231; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.NullReferenceException: Object reference not set to an instance of an object.
   at SyncTrayzor.Xaml.GridViewSortByBehaviour.ApplyColumnSort(GridViewColumnHeader header, GridViewColumn column, ListSortDirection direction) in C:\projects\synctrayzor\src\SyncTrayzor\Xaml\GridViewSortByBehaviour.cs:line 146
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at MS.Internal.FrameworkObject.OnLoaded(RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

```
After that, SyncTrayzor can be started again successfully.

I'm not sure if the crash is easily reproducible though, haven't tested it precisely (need to create conflicts, etc...), but it seem to differ from the previous crashes reported...

**Comment by canton7** [comment] 2016-01-12 09:49
Looks like an evil little race: it's up to whether the visual tree gets fully constructed first, or I try and sort out the column headers. It looks like both might be happening at around about the same time...

**Comment by scienmind** [comment] 2016-01-12 11:31
BTW, seems that "evil little race" isn't as rare, it happened few times more while opening the "Conflict Resolver" from the menu.  (same GridViewSortByBehaviour.cs:line 146 crash)

**Comment by canton7** [comment] 2016-01-12 11:32
Weird, I wonder why I can't reproduce then.

How many conflicts are shown in the conflict resolver when you open it?

**Comment by scienmind** [comment] 2016-01-12 11:35
None conflicts, all in sync (supposedly).
I just opened conflict resolver for the sake of it - and it crashed immediately.
(so I can't tell whether the resolver itself wanted to show anything)

**Comment by canton7** [comment] 2016-01-12 11:57
I wonder if it's a .net version difference...

Mind trying this build https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.1.236/artifacts ?

It won't crash, and it will log the .NET version on startup (`SyncTrazor version XXXX (XXX) started at XXX (.NET version: XXX)`). Could you tell me what .NET version it logs?

**Comment by scienmind** [comment] 2016-01-12 12:15
Unfortunately I can't test it atm (maybe in 10+ h later...). 
For what it worth though, the .NET Framework version is probably "4.5.2" (according to [this](https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx)).

**Comment by canton7** [comment] 2016-01-12 12:18
Right, that is a difference then: I'm on 4.6.

I wonder whether there was a change in behaviour between 4.5.2 and 4.6, where having the table of conflicts hidden would trigger one bit of behaviour when trying to draw on those up/down sort arrows in one version, and a different behaviour in another... That's my best bet right now.

If that is the case, the build I linked to above contains the right fix for this.

**Comment by scienmind** [comment] 2016-01-12 12:24
Personally I can just update to 4.6.1, but not everyone has it, 4.5 is still widespread.
(I'll try the build later today with 4.5.2)

**Comment by canton7** [comment] 2016-01-12 12:25
Yeah - 1.1.2 will go out pretty soon with the fix I linked to above, in case anyone else is affected.

**Comment by scienmind** [comment] 2016-01-13 12:24
I've installed the 1.1.1.236, seem to be stable so far

**Comment by canton7** [comment] 2016-01-13 12:29
Cool, thanks. Just to confirm: does it report it's using 4.5.2 on startup?

The other thing to try is to create a file conflict (copying a file and renaming it from e.g. `foo.txt` to `foo.sync-conflict-20100101-010101.txt` is an easy way to do this), then open the Conflict Resolver. Does the 'File Name' column have a little arrow on it?

**Comment by scienmind** [comment] 2016-01-13 12:38
Yea, seems like 4.5.2:
```
[Debug] SyncTrayzor.Bootstrapper: SyncTrazor version 1.1.1.236 (Amd64) started at C:\Program Files\SyncTrayzor\SyncTrayzor.exe (.NET version: 4.5.2 or later) 
```

And if you mean the "sort by" arrow, it's there:
![image](https://cloud.githubusercontent.com/assets/11633330/12294460/4ed01c3e-ba03-11e5-9a2a-785baa4dc20d.png)

**Comment by canton7** [comment] 2016-01-13 12:40
Cool, that's what I was hoping for thanks!

**Comment by scienmind** [comment] 2016-01-13 12:42
No problem :)

I feel like "Conflict Resolver" makes me greedy, wishing for a `.stversions`'s contents manager now...
;-)

**Closed** 2016-01-13 15:07 UTC
Labels: fix-scheduled

**Comment by canton7** [comment] 2016-01-13 15:38
All in good time! Or contributions welcome :wink:

**Comment by Kugeleis** [comment] 2016-01-30 11:17
Running 1.1.5 64bit on windows 10 and this issue persists.

**Comment by canton7** [comment] 2016-01-30 11:50
@Kungeleis it won't be exactly the same issue. Please open a new github issue, and include the crash message.

**Comment by Kugeleis** [comment] 2016-01-30 12:38
What is the "crash message"? The program stops responding. No message is shown.
[SyncTrayzor.txt](https://github.com/canton7/SyncTrayzor/files/110785/SyncTrayzor.txt)

**Comment by canton7** [comment] 2016-01-30 12:41
That log gives the error message, thanks. This is a different issue to the one @scienmind reported: please open a new github issue and we'll discuss it there.
