### ISSUE TITLE
Window doesn't fit screen

### ISSUE THREAD

**Issue by pmansour22** [canton7/SyncTrayzor#84] opened 2015-05-11 13:24 UTC
I have the size of text and items in Control Panel\All Control Panel Items\Display set to medium (125%).  At that setting the synctrayzor window doesn't fit the screen (I lose the minimise/maximise buttons and the menu toolbar).

Is it possible to get it to fit the screen when the windows display size is not set to the default 100% setting?

**Comment by dodekeract** [comment] 2015-05-11 13:35
What Windows version are you running? What's your display resolution? Can't reproduce this on Windows 8.1 1920x1080.

**Comment by canton7** [comment] 2015-05-11 13:36
Err I guess I could put something in to decrease the default window size if it's too large for the screen.

Can't you just size it to whatever you want, though? After you've done that once, it will remember the size you set. You can move it using e.g. [this](https://askleo.com/i_cant_see_the_top_of_a_window_so_i_cant_minimize_maximize_or_close_what_can_i_do-2/) technique.

**Comment by nille02** [comment] 2015-05-11 13:40
@dodekeract many Laptops come with 1366x786. Instead to change the default, it would be better to check if the dimension is do big for the screen.

**Comment by dodekeract** [comment] 2015-05-11 13:43
@nille02 if that's really OP's issue and @canton7 or somebody else change this behavior then I would add that the default/calculated window position needs to watch for any taskbar (mine is top for my main display) "interference". Steam doesn't properly do it and often moves the window behind my taskbars.

**Comment by canton7** [comment] 2015-05-11 14:17
I've taken the simple approach of constraining the window's initial dimensions (before we get into the business of remembering the window's size/position) to `virtural height - 40` and `virtual width - 40`, 40px being the (large) size of the taskbar. Windows can then take care of positioning it (which in my testing, it does well).

Although - you'll probably find that closing / re-opening SyncTrayzor fixes the issue for you anyway, due to the way that we restore the window's position.

Feel free to re-open the issue if, after the next release, the issue isn't resolved.

**Comment by pmansour22** [comment] 2015-05-12 00:25
Sorry guys for not being more specific, and thanks for the comments.  It's on a little Windows 8 box attached to a TV.  Screen res' is 1920x1080 but the display adapter can only go up to 1360 x 768.  Because I'm sitting 10 feet away I have the display enlarged to 125%.  With that combination though there isn't much screen real estate. 

I should have thought to use the technique canton7 suggested but in the end I didn't need to.  Once I changed the display back to 100% I could resize the screen so when setting it to 125% it fitted okay.

Not a difficult workaround but if you get around to having it fit automatically I'm sure that would help quite a few users.

**Closed** 2015-05-27 11:56 UTC
Labels: fix-scheduled
